<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/transaction.proto

namespace Typedb\Protocol\Transaction;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.Transaction.Client</code>
 */
class Client extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.Transaction.Req reqs = 1;</code>
     */
    private $reqs;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Typedb\Protocol\Transaction\Req[]|\Google\Protobuf\Internal\RepeatedField $reqs
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.Transaction.Req reqs = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getReqs()
    {
        return $this->reqs;
    }

    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.Transaction.Req reqs = 1;</code>
     * @param \Typedb\Protocol\Transaction\Req[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setReqs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Typedb\Protocol\Transaction\Req::class);
        $this->reqs = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Client::class, \Typedb\Protocol\Transaction_Client::class);

