<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/transaction.proto

namespace Typedb\Protocol\Transaction;

use UnexpectedValueException;

/**
 * Protobuf type <code>typedb.protocol.Transaction.Type</code>
 */
class Type
{
    /**
     * Generated from protobuf enum <code>READ = 0;</code>
     */
    const READ = 0;
    /**
     * Generated from protobuf enum <code>WRITE = 1;</code>
     */
    const WRITE = 1;

    private static $valueToName = [
        self::READ => 'READ',
        self::WRITE => 'WRITE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Type::class, \Typedb\Protocol\Transaction_Type::class);

