<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol\Relation\GetPlayersByRoleType;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.Relation.GetPlayersByRoleType.ResPart</code>
 */
class ResPart extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.Relation.GetPlayersByRoleType.RoleTypeWithPlayer role_types_with_players = 1;</code>
     */
    private $role_types_with_players;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Typedb\Protocol\Relation\GetPlayersByRoleType\RoleTypeWithPlayer[]|\Google\Protobuf\Internal\RepeatedField $role_types_with_players
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Concept::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.Relation.GetPlayersByRoleType.RoleTypeWithPlayer role_types_with_players = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRoleTypesWithPlayers()
    {
        return $this->role_types_with_players;
    }

    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.Relation.GetPlayersByRoleType.RoleTypeWithPlayer role_types_with_players = 1;</code>
     * @param \Typedb\Protocol\Relation\GetPlayersByRoleType\RoleTypeWithPlayer[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRoleTypesWithPlayers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Typedb\Protocol\Relation\GetPlayersByRoleType\RoleTypeWithPlayer::class);
        $this->role_types_with_players = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ResPart::class, \Typedb\Protocol\Relation_GetPlayersByRoleType_ResPart::class);

