<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol\Type;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.Type.Req</code>
 */
class Req extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string label = 1;</code>
     */
    protected $label = '';
    /**
     * Generated from protobuf field <code>string scope = 2;</code>
     */
    protected $scope = '';
    protected $req;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $label
     *     @type string $scope
     *     @type \Typedb\Protocol\Type\Delete\Req $type_delete_req
     *           Type method requests
     *     @type \Typedb\Protocol\Type\SetLabel\Req $type_set_label_req
     *     @type \Typedb\Protocol\Type\IsAbstract\Req $type_is_abstract_req
     *     @type \Typedb\Protocol\Type\GetSupertype\Req $type_get_supertype_req
     *     @type \Typedb\Protocol\Type\SetSupertype\Req $type_set_supertype_req
     *     @type \Typedb\Protocol\Type\GetSupertypes\Req $type_get_supertypes_req
     *     @type \Typedb\Protocol\Type\GetSubtypes\Req $type_get_subtypes_req
     *     @type \Typedb\Protocol\RoleType\GetRelationTypes\Req $role_type_get_relation_types_req
     *           RoleType method requests
     *     @type \Typedb\Protocol\RoleType\GetPlayers\Req $role_type_get_players_req
     *     @type \Typedb\Protocol\ThingType\GetInstances\Req $thing_type_get_instances_req
     *           ThingType method requests
     *     @type \Typedb\Protocol\ThingType\SetAbstract\Req $thing_type_set_abstract_req
     *     @type \Typedb\Protocol\ThingType\UnsetAbstract\Req $thing_type_unset_abstract_req
     *     @type \Typedb\Protocol\ThingType\GetOwns\Req $thing_type_get_owns_req
     *     @type \Typedb\Protocol\ThingType\SetOwns\Req $thing_type_set_owns_req
     *     @type \Typedb\Protocol\ThingType\UnsetOwns\Req $thing_type_unset_owns_req
     *     @type \Typedb\Protocol\ThingType\GetPlays\Req $thing_type_get_plays_req
     *     @type \Typedb\Protocol\ThingType\SetPlays\Req $thing_type_set_plays_req
     *     @type \Typedb\Protocol\ThingType\UnsetPlays\Req $thing_type_unset_plays_req
     *     @type \Typedb\Protocol\EntityType\Create\Req $entity_type_create_req
     *           EntityType method requests
     *     @type \Typedb\Protocol\RelationType\Create\Req $relation_type_create_req
     *           RelationType method requests
     *     @type \Typedb\Protocol\RelationType\GetRelatesForRoleLabel\Req $relation_type_get_relates_for_role_label_req
     *     @type \Typedb\Protocol\RelationType\GetRelates\Req $relation_type_get_relates_req
     *     @type \Typedb\Protocol\RelationType\SetRelates\Req $relation_type_set_relates_req
     *     @type \Typedb\Protocol\RelationType\UnsetRelates\Req $relation_type_unset_relates_req
     *     @type \Typedb\Protocol\AttributeType\Put\Req $attribute_type_put_req
     *           AttributeType method requests
     *     @type \Typedb\Protocol\AttributeType\Get\Req $attribute_type_get_req
     *     @type \Typedb\Protocol\AttributeType\GetRegex\Req $attribute_type_get_regex_req
     *     @type \Typedb\Protocol\AttributeType\SetRegex\Req $attribute_type_set_regex_req
     *     @type \Typedb\Protocol\AttributeType\GetOwners\Req $attribute_type_get_owners_req
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Concept::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string label = 1;</code>
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * Generated from protobuf field <code>string label = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->label = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string scope = 2;</code>
     * @return string
     */
    public function getScope()
    {
        return $this->scope;
    }

    /**
     * Generated from protobuf field <code>string scope = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setScope($var)
    {
        GPBUtil::checkString($var, True);
        $this->scope = $var;

        return $this;
    }

    /**
     * Type method requests
     *
     * Generated from protobuf field <code>.typedb.protocol.Type.Delete.Req type_delete_req = 100;</code>
     * @return \Typedb\Protocol\Type\Delete\Req|null
     */
    public function getTypeDeleteReq()
    {
        return $this->readOneof(100);
    }

    public function hasTypeDeleteReq()
    {
        return $this->hasOneof(100);
    }

    /**
     * Type method requests
     *
     * Generated from protobuf field <code>.typedb.protocol.Type.Delete.Req type_delete_req = 100;</code>
     * @param \Typedb\Protocol\Type\Delete\Req $var
     * @return $this
     */
    public function setTypeDeleteReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Type\Delete\Req::class);
        $this->writeOneof(100, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Type.SetLabel.Req type_set_label_req = 101;</code>
     * @return \Typedb\Protocol\Type\SetLabel\Req|null
     */
    public function getTypeSetLabelReq()
    {
        return $this->readOneof(101);
    }

    public function hasTypeSetLabelReq()
    {
        return $this->hasOneof(101);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Type.SetLabel.Req type_set_label_req = 101;</code>
     * @param \Typedb\Protocol\Type\SetLabel\Req $var
     * @return $this
     */
    public function setTypeSetLabelReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Type\SetLabel\Req::class);
        $this->writeOneof(101, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Type.IsAbstract.Req type_is_abstract_req = 102;</code>
     * @return \Typedb\Protocol\Type\IsAbstract\Req|null
     */
    public function getTypeIsAbstractReq()
    {
        return $this->readOneof(102);
    }

    public function hasTypeIsAbstractReq()
    {
        return $this->hasOneof(102);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Type.IsAbstract.Req type_is_abstract_req = 102;</code>
     * @param \Typedb\Protocol\Type\IsAbstract\Req $var
     * @return $this
     */
    public function setTypeIsAbstractReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Type\IsAbstract\Req::class);
        $this->writeOneof(102, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Type.GetSupertype.Req type_get_supertype_req = 103;</code>
     * @return \Typedb\Protocol\Type\GetSupertype\Req|null
     */
    public function getTypeGetSupertypeReq()
    {
        return $this->readOneof(103);
    }

    public function hasTypeGetSupertypeReq()
    {
        return $this->hasOneof(103);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Type.GetSupertype.Req type_get_supertype_req = 103;</code>
     * @param \Typedb\Protocol\Type\GetSupertype\Req $var
     * @return $this
     */
    public function setTypeGetSupertypeReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Type\GetSupertype\Req::class);
        $this->writeOneof(103, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Type.SetSupertype.Req type_set_supertype_req = 104;</code>
     * @return \Typedb\Protocol\Type\SetSupertype\Req|null
     */
    public function getTypeSetSupertypeReq()
    {
        return $this->readOneof(104);
    }

    public function hasTypeSetSupertypeReq()
    {
        return $this->hasOneof(104);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Type.SetSupertype.Req type_set_supertype_req = 104;</code>
     * @param \Typedb\Protocol\Type\SetSupertype\Req $var
     * @return $this
     */
    public function setTypeSetSupertypeReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Type\SetSupertype\Req::class);
        $this->writeOneof(104, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Type.GetSupertypes.Req type_get_supertypes_req = 105;</code>
     * @return \Typedb\Protocol\Type\GetSupertypes\Req|null
     */
    public function getTypeGetSupertypesReq()
    {
        return $this->readOneof(105);
    }

    public function hasTypeGetSupertypesReq()
    {
        return $this->hasOneof(105);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Type.GetSupertypes.Req type_get_supertypes_req = 105;</code>
     * @param \Typedb\Protocol\Type\GetSupertypes\Req $var
     * @return $this
     */
    public function setTypeGetSupertypesReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Type\GetSupertypes\Req::class);
        $this->writeOneof(105, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Type.GetSubtypes.Req type_get_subtypes_req = 106;</code>
     * @return \Typedb\Protocol\Type\GetSubtypes\Req|null
     */
    public function getTypeGetSubtypesReq()
    {
        return $this->readOneof(106);
    }

    public function hasTypeGetSubtypesReq()
    {
        return $this->hasOneof(106);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Type.GetSubtypes.Req type_get_subtypes_req = 106;</code>
     * @param \Typedb\Protocol\Type\GetSubtypes\Req $var
     * @return $this
     */
    public function setTypeGetSubtypesReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Type\GetSubtypes\Req::class);
        $this->writeOneof(106, $var);

        return $this;
    }

    /**
     * RoleType method requests
     *
     * Generated from protobuf field <code>.typedb.protocol.RoleType.GetRelationTypes.Req role_type_get_relation_types_req = 200;</code>
     * @return \Typedb\Protocol\RoleType\GetRelationTypes\Req|null
     */
    public function getRoleTypeGetRelationTypesReq()
    {
        return $this->readOneof(200);
    }

    public function hasRoleTypeGetRelationTypesReq()
    {
        return $this->hasOneof(200);
    }

    /**
     * RoleType method requests
     *
     * Generated from protobuf field <code>.typedb.protocol.RoleType.GetRelationTypes.Req role_type_get_relation_types_req = 200;</code>
     * @param \Typedb\Protocol\RoleType\GetRelationTypes\Req $var
     * @return $this
     */
    public function setRoleTypeGetRelationTypesReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\RoleType\GetRelationTypes\Req::class);
        $this->writeOneof(200, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.RoleType.GetPlayers.Req role_type_get_players_req = 201;</code>
     * @return \Typedb\Protocol\RoleType\GetPlayers\Req|null
     */
    public function getRoleTypeGetPlayersReq()
    {
        return $this->readOneof(201);
    }

    public function hasRoleTypeGetPlayersReq()
    {
        return $this->hasOneof(201);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.RoleType.GetPlayers.Req role_type_get_players_req = 201;</code>
     * @param \Typedb\Protocol\RoleType\GetPlayers\Req $var
     * @return $this
     */
    public function setRoleTypeGetPlayersReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\RoleType\GetPlayers\Req::class);
        $this->writeOneof(201, $var);

        return $this;
    }

    /**
     * ThingType method requests
     *
     * Generated from protobuf field <code>.typedb.protocol.ThingType.GetInstances.Req thing_type_get_instances_req = 300;</code>
     * @return \Typedb\Protocol\ThingType\GetInstances\Req|null
     */
    public function getThingTypeGetInstancesReq()
    {
        return $this->readOneof(300);
    }

    public function hasThingTypeGetInstancesReq()
    {
        return $this->hasOneof(300);
    }

    /**
     * ThingType method requests
     *
     * Generated from protobuf field <code>.typedb.protocol.ThingType.GetInstances.Req thing_type_get_instances_req = 300;</code>
     * @param \Typedb\Protocol\ThingType\GetInstances\Req $var
     * @return $this
     */
    public function setThingTypeGetInstancesReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\ThingType\GetInstances\Req::class);
        $this->writeOneof(300, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.ThingType.SetAbstract.Req thing_type_set_abstract_req = 301;</code>
     * @return \Typedb\Protocol\ThingType\SetAbstract\Req|null
     */
    public function getThingTypeSetAbstractReq()
    {
        return $this->readOneof(301);
    }

    public function hasThingTypeSetAbstractReq()
    {
        return $this->hasOneof(301);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.ThingType.SetAbstract.Req thing_type_set_abstract_req = 301;</code>
     * @param \Typedb\Protocol\ThingType\SetAbstract\Req $var
     * @return $this
     */
    public function setThingTypeSetAbstractReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\ThingType\SetAbstract\Req::class);
        $this->writeOneof(301, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.ThingType.UnsetAbstract.Req thing_type_unset_abstract_req = 302;</code>
     * @return \Typedb\Protocol\ThingType\UnsetAbstract\Req|null
     */
    public function getThingTypeUnsetAbstractReq()
    {
        return $this->readOneof(302);
    }

    public function hasThingTypeUnsetAbstractReq()
    {
        return $this->hasOneof(302);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.ThingType.UnsetAbstract.Req thing_type_unset_abstract_req = 302;</code>
     * @param \Typedb\Protocol\ThingType\UnsetAbstract\Req $var
     * @return $this
     */
    public function setThingTypeUnsetAbstractReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\ThingType\UnsetAbstract\Req::class);
        $this->writeOneof(302, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.ThingType.GetOwns.Req thing_type_get_owns_req = 303;</code>
     * @return \Typedb\Protocol\ThingType\GetOwns\Req|null
     */
    public function getThingTypeGetOwnsReq()
    {
        return $this->readOneof(303);
    }

    public function hasThingTypeGetOwnsReq()
    {
        return $this->hasOneof(303);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.ThingType.GetOwns.Req thing_type_get_owns_req = 303;</code>
     * @param \Typedb\Protocol\ThingType\GetOwns\Req $var
     * @return $this
     */
    public function setThingTypeGetOwnsReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\ThingType\GetOwns\Req::class);
        $this->writeOneof(303, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.ThingType.SetOwns.Req thing_type_set_owns_req = 304;</code>
     * @return \Typedb\Protocol\ThingType\SetOwns\Req|null
     */
    public function getThingTypeSetOwnsReq()
    {
        return $this->readOneof(304);
    }

    public function hasThingTypeSetOwnsReq()
    {
        return $this->hasOneof(304);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.ThingType.SetOwns.Req thing_type_set_owns_req = 304;</code>
     * @param \Typedb\Protocol\ThingType\SetOwns\Req $var
     * @return $this
     */
    public function setThingTypeSetOwnsReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\ThingType\SetOwns\Req::class);
        $this->writeOneof(304, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.ThingType.UnsetOwns.Req thing_type_unset_owns_req = 305;</code>
     * @return \Typedb\Protocol\ThingType\UnsetOwns\Req|null
     */
    public function getThingTypeUnsetOwnsReq()
    {
        return $this->readOneof(305);
    }

    public function hasThingTypeUnsetOwnsReq()
    {
        return $this->hasOneof(305);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.ThingType.UnsetOwns.Req thing_type_unset_owns_req = 305;</code>
     * @param \Typedb\Protocol\ThingType\UnsetOwns\Req $var
     * @return $this
     */
    public function setThingTypeUnsetOwnsReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\ThingType\UnsetOwns\Req::class);
        $this->writeOneof(305, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.ThingType.GetPlays.Req thing_type_get_plays_req = 306;</code>
     * @return \Typedb\Protocol\ThingType\GetPlays\Req|null
     */
    public function getThingTypeGetPlaysReq()
    {
        return $this->readOneof(306);
    }

    public function hasThingTypeGetPlaysReq()
    {
        return $this->hasOneof(306);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.ThingType.GetPlays.Req thing_type_get_plays_req = 306;</code>
     * @param \Typedb\Protocol\ThingType\GetPlays\Req $var
     * @return $this
     */
    public function setThingTypeGetPlaysReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\ThingType\GetPlays\Req::class);
        $this->writeOneof(306, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.ThingType.SetPlays.Req thing_type_set_plays_req = 307;</code>
     * @return \Typedb\Protocol\ThingType\SetPlays\Req|null
     */
    public function getThingTypeSetPlaysReq()
    {
        return $this->readOneof(307);
    }

    public function hasThingTypeSetPlaysReq()
    {
        return $this->hasOneof(307);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.ThingType.SetPlays.Req thing_type_set_plays_req = 307;</code>
     * @param \Typedb\Protocol\ThingType\SetPlays\Req $var
     * @return $this
     */
    public function setThingTypeSetPlaysReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\ThingType\SetPlays\Req::class);
        $this->writeOneof(307, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.ThingType.UnsetPlays.Req thing_type_unset_plays_req = 308;</code>
     * @return \Typedb\Protocol\ThingType\UnsetPlays\Req|null
     */
    public function getThingTypeUnsetPlaysReq()
    {
        return $this->readOneof(308);
    }

    public function hasThingTypeUnsetPlaysReq()
    {
        return $this->hasOneof(308);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.ThingType.UnsetPlays.Req thing_type_unset_plays_req = 308;</code>
     * @param \Typedb\Protocol\ThingType\UnsetPlays\Req $var
     * @return $this
     */
    public function setThingTypeUnsetPlaysReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\ThingType\UnsetPlays\Req::class);
        $this->writeOneof(308, $var);

        return $this;
    }

    /**
     * EntityType method requests
     *
     * Generated from protobuf field <code>.typedb.protocol.EntityType.Create.Req entity_type_create_req = 400;</code>
     * @return \Typedb\Protocol\EntityType\Create\Req|null
     */
    public function getEntityTypeCreateReq()
    {
        return $this->readOneof(400);
    }

    public function hasEntityTypeCreateReq()
    {
        return $this->hasOneof(400);
    }

    /**
     * EntityType method requests
     *
     * Generated from protobuf field <code>.typedb.protocol.EntityType.Create.Req entity_type_create_req = 400;</code>
     * @param \Typedb\Protocol\EntityType\Create\Req $var
     * @return $this
     */
    public function setEntityTypeCreateReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\EntityType\Create\Req::class);
        $this->writeOneof(400, $var);

        return $this;
    }

    /**
     * RelationType method requests
     *
     * Generated from protobuf field <code>.typedb.protocol.RelationType.Create.Req relation_type_create_req = 500;</code>
     * @return \Typedb\Protocol\RelationType\Create\Req|null
     */
    public function getRelationTypeCreateReq()
    {
        return $this->readOneof(500);
    }

    public function hasRelationTypeCreateReq()
    {
        return $this->hasOneof(500);
    }

    /**
     * RelationType method requests
     *
     * Generated from protobuf field <code>.typedb.protocol.RelationType.Create.Req relation_type_create_req = 500;</code>
     * @param \Typedb\Protocol\RelationType\Create\Req $var
     * @return $this
     */
    public function setRelationTypeCreateReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\RelationType\Create\Req::class);
        $this->writeOneof(500, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.RelationType.GetRelatesForRoleLabel.Req relation_type_get_relates_for_role_label_req = 501;</code>
     * @return \Typedb\Protocol\RelationType\GetRelatesForRoleLabel\Req|null
     */
    public function getRelationTypeGetRelatesForRoleLabelReq()
    {
        return $this->readOneof(501);
    }

    public function hasRelationTypeGetRelatesForRoleLabelReq()
    {
        return $this->hasOneof(501);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.RelationType.GetRelatesForRoleLabel.Req relation_type_get_relates_for_role_label_req = 501;</code>
     * @param \Typedb\Protocol\RelationType\GetRelatesForRoleLabel\Req $var
     * @return $this
     */
    public function setRelationTypeGetRelatesForRoleLabelReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\RelationType\GetRelatesForRoleLabel\Req::class);
        $this->writeOneof(501, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.RelationType.GetRelates.Req relation_type_get_relates_req = 502;</code>
     * @return \Typedb\Protocol\RelationType\GetRelates\Req|null
     */
    public function getRelationTypeGetRelatesReq()
    {
        return $this->readOneof(502);
    }

    public function hasRelationTypeGetRelatesReq()
    {
        return $this->hasOneof(502);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.RelationType.GetRelates.Req relation_type_get_relates_req = 502;</code>
     * @param \Typedb\Protocol\RelationType\GetRelates\Req $var
     * @return $this
     */
    public function setRelationTypeGetRelatesReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\RelationType\GetRelates\Req::class);
        $this->writeOneof(502, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.RelationType.SetRelates.Req relation_type_set_relates_req = 503;</code>
     * @return \Typedb\Protocol\RelationType\SetRelates\Req|null
     */
    public function getRelationTypeSetRelatesReq()
    {
        return $this->readOneof(503);
    }

    public function hasRelationTypeSetRelatesReq()
    {
        return $this->hasOneof(503);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.RelationType.SetRelates.Req relation_type_set_relates_req = 503;</code>
     * @param \Typedb\Protocol\RelationType\SetRelates\Req $var
     * @return $this
     */
    public function setRelationTypeSetRelatesReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\RelationType\SetRelates\Req::class);
        $this->writeOneof(503, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.RelationType.UnsetRelates.Req relation_type_unset_relates_req = 504;</code>
     * @return \Typedb\Protocol\RelationType\UnsetRelates\Req|null
     */
    public function getRelationTypeUnsetRelatesReq()
    {
        return $this->readOneof(504);
    }

    public function hasRelationTypeUnsetRelatesReq()
    {
        return $this->hasOneof(504);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.RelationType.UnsetRelates.Req relation_type_unset_relates_req = 504;</code>
     * @param \Typedb\Protocol\RelationType\UnsetRelates\Req $var
     * @return $this
     */
    public function setRelationTypeUnsetRelatesReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\RelationType\UnsetRelates\Req::class);
        $this->writeOneof(504, $var);

        return $this;
    }

    /**
     * AttributeType method requests
     *
     * Generated from protobuf field <code>.typedb.protocol.AttributeType.Put.Req attribute_type_put_req = 600;</code>
     * @return \Typedb\Protocol\AttributeType\Put\Req|null
     */
    public function getAttributeTypePutReq()
    {
        return $this->readOneof(600);
    }

    public function hasAttributeTypePutReq()
    {
        return $this->hasOneof(600);
    }

    /**
     * AttributeType method requests
     *
     * Generated from protobuf field <code>.typedb.protocol.AttributeType.Put.Req attribute_type_put_req = 600;</code>
     * @param \Typedb\Protocol\AttributeType\Put\Req $var
     * @return $this
     */
    public function setAttributeTypePutReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\AttributeType\Put\Req::class);
        $this->writeOneof(600, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.AttributeType.Get.Req attribute_type_get_req = 601;</code>
     * @return \Typedb\Protocol\AttributeType\Get\Req|null
     */
    public function getAttributeTypeGetReq()
    {
        return $this->readOneof(601);
    }

    public function hasAttributeTypeGetReq()
    {
        return $this->hasOneof(601);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.AttributeType.Get.Req attribute_type_get_req = 601;</code>
     * @param \Typedb\Protocol\AttributeType\Get\Req $var
     * @return $this
     */
    public function setAttributeTypeGetReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\AttributeType\Get\Req::class);
        $this->writeOneof(601, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.AttributeType.GetRegex.Req attribute_type_get_regex_req = 602;</code>
     * @return \Typedb\Protocol\AttributeType\GetRegex\Req|null
     */
    public function getAttributeTypeGetRegexReq()
    {
        return $this->readOneof(602);
    }

    public function hasAttributeTypeGetRegexReq()
    {
        return $this->hasOneof(602);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.AttributeType.GetRegex.Req attribute_type_get_regex_req = 602;</code>
     * @param \Typedb\Protocol\AttributeType\GetRegex\Req $var
     * @return $this
     */
    public function setAttributeTypeGetRegexReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\AttributeType\GetRegex\Req::class);
        $this->writeOneof(602, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.AttributeType.SetRegex.Req attribute_type_set_regex_req = 603;</code>
     * @return \Typedb\Protocol\AttributeType\SetRegex\Req|null
     */
    public function getAttributeTypeSetRegexReq()
    {
        return $this->readOneof(603);
    }

    public function hasAttributeTypeSetRegexReq()
    {
        return $this->hasOneof(603);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.AttributeType.SetRegex.Req attribute_type_set_regex_req = 603;</code>
     * @param \Typedb\Protocol\AttributeType\SetRegex\Req $var
     * @return $this
     */
    public function setAttributeTypeSetRegexReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\AttributeType\SetRegex\Req::class);
        $this->writeOneof(603, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.AttributeType.GetOwners.Req attribute_type_get_owners_req = 604;</code>
     * @return \Typedb\Protocol\AttributeType\GetOwners\Req|null
     */
    public function getAttributeTypeGetOwnersReq()
    {
        return $this->readOneof(604);
    }

    public function hasAttributeTypeGetOwnersReq()
    {
        return $this->hasOneof(604);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.AttributeType.GetOwners.Req attribute_type_get_owners_req = 604;</code>
     * @param \Typedb\Protocol\AttributeType\GetOwners\Req $var
     * @return $this
     */
    public function setAttributeTypeGetOwnersReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\AttributeType\GetOwners\Req::class);
        $this->writeOneof(604, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getReq()
    {
        return $this->whichOneof("req");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Req::class, \Typedb\Protocol\Type_Req::class);

