<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol\Type;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.Type.ResPart</code>
 */
class ResPart extends \Google\Protobuf\Internal\Message
{
    protected $res;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Typedb\Protocol\Type\GetSupertypes\ResPart $type_get_supertypes_res_part
     *           Type method responses
     *     @type \Typedb\Protocol\Type\GetSubtypes\ResPart $type_get_subtypes_res_part
     *     @type \Typedb\Protocol\RoleType\GetRelationTypes\ResPart $role_type_get_relation_types_res_part
     *           RoleType method responses
     *     @type \Typedb\Protocol\RoleType\GetPlayers\ResPart $role_type_get_players_res_part
     *     @type \Typedb\Protocol\ThingType\GetInstances\ResPart $thing_type_get_instances_res_part
     *           ThingType method responses
     *     @type \Typedb\Protocol\ThingType\GetOwns\ResPart $thing_type_get_owns_res_part
     *     @type \Typedb\Protocol\ThingType\GetPlays\ResPart $thing_type_get_plays_res_part
     *     @type \Typedb\Protocol\RelationType\GetRelates\ResPart $relation_type_get_relates_res_part
     *           RelationType method responses
     *     @type \Typedb\Protocol\AttributeType\GetOwners\ResPart $attribute_type_get_owners_res_part
     *           AttributeType method responses
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Concept::initOnce();
        parent::__construct($data);
    }

    /**
     * Type method responses
     *
     * Generated from protobuf field <code>.typedb.protocol.Type.GetSupertypes.ResPart type_get_supertypes_res_part = 100;</code>
     * @return \Typedb\Protocol\Type\GetSupertypes\ResPart|null
     */
    public function getTypeGetSupertypesResPart()
    {
        return $this->readOneof(100);
    }

    public function hasTypeGetSupertypesResPart()
    {
        return $this->hasOneof(100);
    }

    /**
     * Type method responses
     *
     * Generated from protobuf field <code>.typedb.protocol.Type.GetSupertypes.ResPart type_get_supertypes_res_part = 100;</code>
     * @param \Typedb\Protocol\Type\GetSupertypes\ResPart $var
     * @return $this
     */
    public function setTypeGetSupertypesResPart($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Type\GetSupertypes\ResPart::class);
        $this->writeOneof(100, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Type.GetSubtypes.ResPart type_get_subtypes_res_part = 101;</code>
     * @return \Typedb\Protocol\Type\GetSubtypes\ResPart|null
     */
    public function getTypeGetSubtypesResPart()
    {
        return $this->readOneof(101);
    }

    public function hasTypeGetSubtypesResPart()
    {
        return $this->hasOneof(101);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Type.GetSubtypes.ResPart type_get_subtypes_res_part = 101;</code>
     * @param \Typedb\Protocol\Type\GetSubtypes\ResPart $var
     * @return $this
     */
    public function setTypeGetSubtypesResPart($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Type\GetSubtypes\ResPart::class);
        $this->writeOneof(101, $var);

        return $this;
    }

    /**
     * RoleType method responses
     *
     * Generated from protobuf field <code>.typedb.protocol.RoleType.GetRelationTypes.ResPart role_type_get_relation_types_res_part = 200;</code>
     * @return \Typedb\Protocol\RoleType\GetRelationTypes\ResPart|null
     */
    public function getRoleTypeGetRelationTypesResPart()
    {
        return $this->readOneof(200);
    }

    public function hasRoleTypeGetRelationTypesResPart()
    {
        return $this->hasOneof(200);
    }

    /**
     * RoleType method responses
     *
     * Generated from protobuf field <code>.typedb.protocol.RoleType.GetRelationTypes.ResPart role_type_get_relation_types_res_part = 200;</code>
     * @param \Typedb\Protocol\RoleType\GetRelationTypes\ResPart $var
     * @return $this
     */
    public function setRoleTypeGetRelationTypesResPart($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\RoleType\GetRelationTypes\ResPart::class);
        $this->writeOneof(200, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.RoleType.GetPlayers.ResPart role_type_get_players_res_part = 201;</code>
     * @return \Typedb\Protocol\RoleType\GetPlayers\ResPart|null
     */
    public function getRoleTypeGetPlayersResPart()
    {
        return $this->readOneof(201);
    }

    public function hasRoleTypeGetPlayersResPart()
    {
        return $this->hasOneof(201);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.RoleType.GetPlayers.ResPart role_type_get_players_res_part = 201;</code>
     * @param \Typedb\Protocol\RoleType\GetPlayers\ResPart $var
     * @return $this
     */
    public function setRoleTypeGetPlayersResPart($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\RoleType\GetPlayers\ResPart::class);
        $this->writeOneof(201, $var);

        return $this;
    }

    /**
     * ThingType method responses
     *
     * Generated from protobuf field <code>.typedb.protocol.ThingType.GetInstances.ResPart thing_type_get_instances_res_part = 300;</code>
     * @return \Typedb\Protocol\ThingType\GetInstances\ResPart|null
     */
    public function getThingTypeGetInstancesResPart()
    {
        return $this->readOneof(300);
    }

    public function hasThingTypeGetInstancesResPart()
    {
        return $this->hasOneof(300);
    }

    /**
     * ThingType method responses
     *
     * Generated from protobuf field <code>.typedb.protocol.ThingType.GetInstances.ResPart thing_type_get_instances_res_part = 300;</code>
     * @param \Typedb\Protocol\ThingType\GetInstances\ResPart $var
     * @return $this
     */
    public function setThingTypeGetInstancesResPart($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\ThingType\GetInstances\ResPart::class);
        $this->writeOneof(300, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.ThingType.GetOwns.ResPart thing_type_get_owns_res_part = 301;</code>
     * @return \Typedb\Protocol\ThingType\GetOwns\ResPart|null
     */
    public function getThingTypeGetOwnsResPart()
    {
        return $this->readOneof(301);
    }

    public function hasThingTypeGetOwnsResPart()
    {
        return $this->hasOneof(301);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.ThingType.GetOwns.ResPart thing_type_get_owns_res_part = 301;</code>
     * @param \Typedb\Protocol\ThingType\GetOwns\ResPart $var
     * @return $this
     */
    public function setThingTypeGetOwnsResPart($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\ThingType\GetOwns\ResPart::class);
        $this->writeOneof(301, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.ThingType.GetPlays.ResPart thing_type_get_plays_res_part = 302;</code>
     * @return \Typedb\Protocol\ThingType\GetPlays\ResPart|null
     */
    public function getThingTypeGetPlaysResPart()
    {
        return $this->readOneof(302);
    }

    public function hasThingTypeGetPlaysResPart()
    {
        return $this->hasOneof(302);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.ThingType.GetPlays.ResPart thing_type_get_plays_res_part = 302;</code>
     * @param \Typedb\Protocol\ThingType\GetPlays\ResPart $var
     * @return $this
     */
    public function setThingTypeGetPlaysResPart($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\ThingType\GetPlays\ResPart::class);
        $this->writeOneof(302, $var);

        return $this;
    }

    /**
     * RelationType method responses
     *
     * Generated from protobuf field <code>.typedb.protocol.RelationType.GetRelates.ResPart relation_type_get_relates_res_part = 500;</code>
     * @return \Typedb\Protocol\RelationType\GetRelates\ResPart|null
     */
    public function getRelationTypeGetRelatesResPart()
    {
        return $this->readOneof(500);
    }

    public function hasRelationTypeGetRelatesResPart()
    {
        return $this->hasOneof(500);
    }

    /**
     * RelationType method responses
     *
     * Generated from protobuf field <code>.typedb.protocol.RelationType.GetRelates.ResPart relation_type_get_relates_res_part = 500;</code>
     * @param \Typedb\Protocol\RelationType\GetRelates\ResPart $var
     * @return $this
     */
    public function setRelationTypeGetRelatesResPart($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\RelationType\GetRelates\ResPart::class);
        $this->writeOneof(500, $var);

        return $this;
    }

    /**
     * AttributeType method responses
     *
     * Generated from protobuf field <code>.typedb.protocol.AttributeType.GetOwners.ResPart attribute_type_get_owners_res_part = 600;</code>
     * @return \Typedb\Protocol\AttributeType\GetOwners\ResPart|null
     */
    public function getAttributeTypeGetOwnersResPart()
    {
        return $this->readOneof(600);
    }

    public function hasAttributeTypeGetOwnersResPart()
    {
        return $this->hasOneof(600);
    }

    /**
     * AttributeType method responses
     *
     * Generated from protobuf field <code>.typedb.protocol.AttributeType.GetOwners.ResPart attribute_type_get_owners_res_part = 600;</code>
     * @param \Typedb\Protocol\AttributeType\GetOwners\ResPart $var
     * @return $this
     */
    public function setAttributeTypeGetOwnersResPart($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\AttributeType\GetOwners\ResPart::class);
        $this->writeOneof(600, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getRes()
    {
        return $this->whichOneof("res");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ResPart::class, \Typedb\Protocol\Type_ResPart::class);

