<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/core_database.proto

namespace Typedb\Protocol\CoreDatabaseManager\Contains;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.CoreDatabaseManager.Contains.Res</code>
 */
class Res extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool contains = 1;</code>
     */
    protected $contains = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $contains
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Core\CoreDatabase::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool contains = 1;</code>
     * @return bool
     */
    public function getContains()
    {
        return $this->contains;
    }

    /**
     * Generated from protobuf field <code>bool contains = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setContains($var)
    {
        GPBUtil::checkBool($var);
        $this->contains = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Res::class, \Typedb\Protocol\CoreDatabaseManager_Contains_Res::class);

