<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol\ThingType\GetInstances;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.ThingType.GetInstances.ResPart</code>
 */
class ResPart extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.Thing things = 1;</code>
     */
    private $things;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Typedb\Protocol\Thing[]|\Google\Protobuf\Internal\RepeatedField $things
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Concept::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.Thing things = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getThings()
    {
        return $this->things;
    }

    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.Thing things = 1;</code>
     * @param \Typedb\Protocol\Thing[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setThings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Typedb\Protocol\Thing::class);
        $this->things = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ResPart::class, \Typedb\Protocol\ThingType_GetInstances_ResPart::class);

