<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/query.proto

namespace Typedb\Protocol\QueryManager\Update;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.QueryManager.Update.ResPart</code>
 */
class ResPart extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.ConceptMap answers = 1;</code>
     */
    private $answers;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Typedb\Protocol\ConceptMap[]|\Google\Protobuf\Internal\RepeatedField $answers
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.ConceptMap answers = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAnswers()
    {
        return $this->answers;
    }

    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.ConceptMap answers = 1;</code>
     * @param \Typedb\Protocol\ConceptMap[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAnswers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Typedb\Protocol\ConceptMap::class);
        $this->answers = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ResPart::class, \Typedb\Protocol\QueryManager_Update_ResPart::class);

