<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/transaction.proto

namespace Typedb\Protocol\Transaction\Stream;

use UnexpectedValueException;

/**
 * Protobuf type <code>typedb.protocol.Transaction.Stream.State</code>
 */
class State
{
    /**
     * Generated from protobuf enum <code>CONTINUE = 0;</code>
     */
    const PBCONTINUE = 0;
    /**
     * Generated from protobuf enum <code>DONE = 1;</code>
     */
    const DONE = 1;

    private static $valueToName = [
        self::PBCONTINUE => 'PBCONTINUE',
        self::DONE => 'DONE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(State::class, \Typedb\Protocol\Transaction_Stream_State::class);

