<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/session.proto

namespace Typedb\Protocol\Session\Pulse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.Session.Pulse.Res</code>
 */
class Res extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool alive = 1;</code>
     */
    protected $alive = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $alive
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Session::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool alive = 1;</code>
     * @return bool
     */
    public function getAlive()
    {
        return $this->alive;
    }

    /**
     * Generated from protobuf field <code>bool alive = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setAlive($var)
    {
        GPBUtil::checkBool($var);
        $this->alive = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Res::class, \Typedb\Protocol\Session_Pulse_Res::class);

