<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster/cluster_database.proto

namespace Typedb\Protocol\ClusterDatabaseManager\All;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.ClusterDatabaseManager.All.Res</code>
 */
class Res extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.ClusterDatabase databases = 1;</code>
     */
    private $databases;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Typedb\Protocol\ClusterDatabase[]|\Google\Protobuf\Internal\RepeatedField $databases
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cluster\ClusterDatabase::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.ClusterDatabase databases = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDatabases()
    {
        return $this->databases;
    }

    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.ClusterDatabase databases = 1;</code>
     * @param \Typedb\Protocol\ClusterDatabase[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDatabases($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Typedb\Protocol\ClusterDatabase::class);
        $this->databases = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Res::class, \Typedb\Protocol\ClusterDatabaseManager_All_Res::class);

