<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol\RelationType\Create;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.RelationType.Create.Res</code>
 */
class Res extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.typedb.protocol.Thing relation = 1;</code>
     */
    protected $relation = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Typedb\Protocol\Thing $relation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Concept::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Thing relation = 1;</code>
     * @return \Typedb\Protocol\Thing|null
     */
    public function getRelation()
    {
        return $this->relation;
    }

    public function hasRelation()
    {
        return isset($this->relation);
    }

    public function clearRelation()
    {
        unset($this->relation);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Thing relation = 1;</code>
     * @param \Typedb\Protocol\Thing $var
     * @return $this
     */
    public function setRelation($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Thing::class);
        $this->relation = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Res::class, \Typedb\Protocol\RelationType_Create_Res::class);

