<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol\Thing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.Thing.Req</code>
 */
class Req extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes iid = 1;</code>
     */
    protected $iid = '';
    protected $req;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $iid
     *     @type \Typedb\Protocol\Thing\Delete\Req $thing_delete_req
     *           Thing method requests
     *     @type \Typedb\Protocol\Thing\GetType\Req $thing_get_type_req
     *     @type \Typedb\Protocol\Thing\GetHas\Req $thing_get_has_req
     *     @type \Typedb\Protocol\Thing\SetHas\Req $thing_set_has_req
     *     @type \Typedb\Protocol\Thing\UnsetHas\Req $thing_unset_has_req
     *     @type \Typedb\Protocol\Thing\GetRelations\Req $thing_get_relations_req
     *     @type \Typedb\Protocol\Thing\GetPlaying\Req $thing_get_playing_req
     *     @type \Typedb\Protocol\Relation\AddPlayer\Req $relation_add_player_req
     *           Relation method requests
     *     @type \Typedb\Protocol\Relation\RemovePlayer\Req $relation_remove_player_req
     *     @type \Typedb\Protocol\Relation\GetPlayers\Req $relation_get_players_req
     *     @type \Typedb\Protocol\Relation\GetPlayersByRoleType\Req $relation_get_players_by_role_type_req
     *     @type \Typedb\Protocol\Relation\GetRelating\Req $relation_get_relating_req
     *     @type \Typedb\Protocol\Attribute\GetOwners\Req $attribute_get_owners_req
     *           Attribute method requests
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Concept::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes iid = 1;</code>
     * @return string
     */
    public function getIid()
    {
        return $this->iid;
    }

    /**
     * Generated from protobuf field <code>bytes iid = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIid($var)
    {
        GPBUtil::checkString($var, False);
        $this->iid = $var;

        return $this;
    }

    /**
     * Thing method requests
     *
     * Generated from protobuf field <code>.typedb.protocol.Thing.Delete.Req thing_delete_req = 100;</code>
     * @return \Typedb\Protocol\Thing\Delete\Req|null
     */
    public function getThingDeleteReq()
    {
        return $this->readOneof(100);
    }

    public function hasThingDeleteReq()
    {
        return $this->hasOneof(100);
    }

    /**
     * Thing method requests
     *
     * Generated from protobuf field <code>.typedb.protocol.Thing.Delete.Req thing_delete_req = 100;</code>
     * @param \Typedb\Protocol\Thing\Delete\Req $var
     * @return $this
     */
    public function setThingDeleteReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Thing\Delete\Req::class);
        $this->writeOneof(100, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Thing.GetType.Req thing_get_type_req = 101;</code>
     * @return \Typedb\Protocol\Thing\GetType\Req|null
     */
    public function getThingGetTypeReq()
    {
        return $this->readOneof(101);
    }

    public function hasThingGetTypeReq()
    {
        return $this->hasOneof(101);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Thing.GetType.Req thing_get_type_req = 101;</code>
     * @param \Typedb\Protocol\Thing\GetType\Req $var
     * @return $this
     */
    public function setThingGetTypeReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Thing\GetType\Req::class);
        $this->writeOneof(101, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Thing.GetHas.Req thing_get_has_req = 102;</code>
     * @return \Typedb\Protocol\Thing\GetHas\Req|null
     */
    public function getThingGetHasReq()
    {
        return $this->readOneof(102);
    }

    public function hasThingGetHasReq()
    {
        return $this->hasOneof(102);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Thing.GetHas.Req thing_get_has_req = 102;</code>
     * @param \Typedb\Protocol\Thing\GetHas\Req $var
     * @return $this
     */
    public function setThingGetHasReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Thing\GetHas\Req::class);
        $this->writeOneof(102, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Thing.SetHas.Req thing_set_has_req = 103;</code>
     * @return \Typedb\Protocol\Thing\SetHas\Req|null
     */
    public function getThingSetHasReq()
    {
        return $this->readOneof(103);
    }

    public function hasThingSetHasReq()
    {
        return $this->hasOneof(103);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Thing.SetHas.Req thing_set_has_req = 103;</code>
     * @param \Typedb\Protocol\Thing\SetHas\Req $var
     * @return $this
     */
    public function setThingSetHasReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Thing\SetHas\Req::class);
        $this->writeOneof(103, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Thing.UnsetHas.Req thing_unset_has_req = 104;</code>
     * @return \Typedb\Protocol\Thing\UnsetHas\Req|null
     */
    public function getThingUnsetHasReq()
    {
        return $this->readOneof(104);
    }

    public function hasThingUnsetHasReq()
    {
        return $this->hasOneof(104);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Thing.UnsetHas.Req thing_unset_has_req = 104;</code>
     * @param \Typedb\Protocol\Thing\UnsetHas\Req $var
     * @return $this
     */
    public function setThingUnsetHasReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Thing\UnsetHas\Req::class);
        $this->writeOneof(104, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Thing.GetRelations.Req thing_get_relations_req = 105;</code>
     * @return \Typedb\Protocol\Thing\GetRelations\Req|null
     */
    public function getThingGetRelationsReq()
    {
        return $this->readOneof(105);
    }

    public function hasThingGetRelationsReq()
    {
        return $this->hasOneof(105);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Thing.GetRelations.Req thing_get_relations_req = 105;</code>
     * @param \Typedb\Protocol\Thing\GetRelations\Req $var
     * @return $this
     */
    public function setThingGetRelationsReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Thing\GetRelations\Req::class);
        $this->writeOneof(105, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Thing.GetPlaying.Req thing_get_playing_req = 106;</code>
     * @return \Typedb\Protocol\Thing\GetPlaying\Req|null
     */
    public function getThingGetPlayingReq()
    {
        return $this->readOneof(106);
    }

    public function hasThingGetPlayingReq()
    {
        return $this->hasOneof(106);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Thing.GetPlaying.Req thing_get_playing_req = 106;</code>
     * @param \Typedb\Protocol\Thing\GetPlaying\Req $var
     * @return $this
     */
    public function setThingGetPlayingReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Thing\GetPlaying\Req::class);
        $this->writeOneof(106, $var);

        return $this;
    }

    /**
     * Relation method requests
     *
     * Generated from protobuf field <code>.typedb.protocol.Relation.AddPlayer.Req relation_add_player_req = 200;</code>
     * @return \Typedb\Protocol\Relation\AddPlayer\Req|null
     */
    public function getRelationAddPlayerReq()
    {
        return $this->readOneof(200);
    }

    public function hasRelationAddPlayerReq()
    {
        return $this->hasOneof(200);
    }

    /**
     * Relation method requests
     *
     * Generated from protobuf field <code>.typedb.protocol.Relation.AddPlayer.Req relation_add_player_req = 200;</code>
     * @param \Typedb\Protocol\Relation\AddPlayer\Req $var
     * @return $this
     */
    public function setRelationAddPlayerReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Relation\AddPlayer\Req::class);
        $this->writeOneof(200, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Relation.RemovePlayer.Req relation_remove_player_req = 201;</code>
     * @return \Typedb\Protocol\Relation\RemovePlayer\Req|null
     */
    public function getRelationRemovePlayerReq()
    {
        return $this->readOneof(201);
    }

    public function hasRelationRemovePlayerReq()
    {
        return $this->hasOneof(201);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Relation.RemovePlayer.Req relation_remove_player_req = 201;</code>
     * @param \Typedb\Protocol\Relation\RemovePlayer\Req $var
     * @return $this
     */
    public function setRelationRemovePlayerReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Relation\RemovePlayer\Req::class);
        $this->writeOneof(201, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Relation.GetPlayers.Req relation_get_players_req = 202;</code>
     * @return \Typedb\Protocol\Relation\GetPlayers\Req|null
     */
    public function getRelationGetPlayersReq()
    {
        return $this->readOneof(202);
    }

    public function hasRelationGetPlayersReq()
    {
        return $this->hasOneof(202);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Relation.GetPlayers.Req relation_get_players_req = 202;</code>
     * @param \Typedb\Protocol\Relation\GetPlayers\Req $var
     * @return $this
     */
    public function setRelationGetPlayersReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Relation\GetPlayers\Req::class);
        $this->writeOneof(202, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Relation.GetPlayersByRoleType.Req relation_get_players_by_role_type_req = 203;</code>
     * @return \Typedb\Protocol\Relation\GetPlayersByRoleType\Req|null
     */
    public function getRelationGetPlayersByRoleTypeReq()
    {
        return $this->readOneof(203);
    }

    public function hasRelationGetPlayersByRoleTypeReq()
    {
        return $this->hasOneof(203);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Relation.GetPlayersByRoleType.Req relation_get_players_by_role_type_req = 203;</code>
     * @param \Typedb\Protocol\Relation\GetPlayersByRoleType\Req $var
     * @return $this
     */
    public function setRelationGetPlayersByRoleTypeReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Relation\GetPlayersByRoleType\Req::class);
        $this->writeOneof(203, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Relation.GetRelating.Req relation_get_relating_req = 204;</code>
     * @return \Typedb\Protocol\Relation\GetRelating\Req|null
     */
    public function getRelationGetRelatingReq()
    {
        return $this->readOneof(204);
    }

    public function hasRelationGetRelatingReq()
    {
        return $this->hasOneof(204);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Relation.GetRelating.Req relation_get_relating_req = 204;</code>
     * @param \Typedb\Protocol\Relation\GetRelating\Req $var
     * @return $this
     */
    public function setRelationGetRelatingReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Relation\GetRelating\Req::class);
        $this->writeOneof(204, $var);

        return $this;
    }

    /**
     * Attribute method requests
     *
     * Generated from protobuf field <code>.typedb.protocol.Attribute.GetOwners.Req attribute_get_owners_req = 300;</code>
     * @return \Typedb\Protocol\Attribute\GetOwners\Req|null
     */
    public function getAttributeGetOwnersReq()
    {
        return $this->readOneof(300);
    }

    public function hasAttributeGetOwnersReq()
    {
        return $this->hasOneof(300);
    }

    /**
     * Attribute method requests
     *
     * Generated from protobuf field <code>.typedb.protocol.Attribute.GetOwners.Req attribute_get_owners_req = 300;</code>
     * @param \Typedb\Protocol\Attribute\GetOwners\Req $var
     * @return $this
     */
    public function setAttributeGetOwnersReq($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Attribute\GetOwners\Req::class);
        $this->writeOneof(300, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getReq()
    {
        return $this->whichOneof("req");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Req::class, \Typedb\Protocol\Thing_Req::class);

