<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol\ThingType\SetOwns;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.ThingType.SetOwns.Req</code>
 */
class Req extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.typedb.protocol.Type attribute_type = 1;</code>
     */
    protected $attribute_type = null;
    /**
     * Generated from protobuf field <code>bool is_key = 3;</code>
     */
    protected $is_key = false;
    protected $overridden;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Typedb\Protocol\Type $attribute_type
     *     @type \Typedb\Protocol\Type $overridden_type
     *     @type bool $is_key
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Concept::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Type attribute_type = 1;</code>
     * @return \Typedb\Protocol\Type|null
     */
    public function getAttributeType()
    {
        return $this->attribute_type;
    }

    public function hasAttributeType()
    {
        return isset($this->attribute_type);
    }

    public function clearAttributeType()
    {
        unset($this->attribute_type);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Type attribute_type = 1;</code>
     * @param \Typedb\Protocol\Type $var
     * @return $this
     */
    public function setAttributeType($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Type::class);
        $this->attribute_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Type overridden_type = 2;</code>
     * @return \Typedb\Protocol\Type|null
     */
    public function getOverriddenType()
    {
        return $this->readOneof(2);
    }

    public function hasOverriddenType()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Type overridden_type = 2;</code>
     * @param \Typedb\Protocol\Type $var
     * @return $this
     */
    public function setOverriddenType($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Type::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_key = 3;</code>
     * @return bool
     */
    public function getIsKey()
    {
        return $this->is_key;
    }

    /**
     * Generated from protobuf field <code>bool is_key = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsKey($var)
    {
        GPBUtil::checkBool($var);
        $this->is_key = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getOverridden()
    {
        return $this->whichOneof("overridden");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Req::class, \Typedb\Protocol\ThingType_SetOwns_Req::class);

