<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster/cluster_database.proto

namespace Typedb\Protocol\ClusterDatabase;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.ClusterDatabase.Replica</code>
 */
class Replica extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string address = 1;</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>bool primary = 2;</code>
     */
    protected $primary = false;
    /**
     * Generated from protobuf field <code>bool preferred = 3;</code>
     */
    protected $preferred = false;
    /**
     * Generated from protobuf field <code>int64 term = 4;</code>
     */
    protected $term = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $address
     *     @type bool $primary
     *     @type bool $preferred
     *     @type int|string $term
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cluster\ClusterDatabase::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string address = 1;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool primary = 2;</code>
     * @return bool
     */
    public function getPrimary()
    {
        return $this->primary;
    }

    /**
     * Generated from protobuf field <code>bool primary = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setPrimary($var)
    {
        GPBUtil::checkBool($var);
        $this->primary = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool preferred = 3;</code>
     * @return bool
     */
    public function getPreferred()
    {
        return $this->preferred;
    }

    /**
     * Generated from protobuf field <code>bool preferred = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setPreferred($var)
    {
        GPBUtil::checkBool($var);
        $this->preferred = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 term = 4;</code>
     * @return int|string
     */
    public function getTerm()
    {
        return $this->term;
    }

    /**
     * Generated from protobuf field <code>int64 term = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTerm($var)
    {
        GPBUtil::checkInt64($var);
        $this->term = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Replica::class, \Typedb\Protocol\ClusterDatabase_Replica::class);

