<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol\AttributeType\GetOwners;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.AttributeType.GetOwners.Req</code>
 */
class Req extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool only_key = 1;</code>
     */
    protected $only_key = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $only_key
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Concept::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool only_key = 1;</code>
     * @return bool
     */
    public function getOnlyKey()
    {
        return $this->only_key;
    }

    /**
     * Generated from protobuf field <code>bool only_key = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setOnlyKey($var)
    {
        GPBUtil::checkBool($var);
        $this->only_key = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Req::class, \Typedb\Protocol\AttributeType_GetOwners_Req::class);

