<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster/cluster_service.proto

namespace GPBMetadata\Cluster;

class ClusterService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Cluster\ClusterServer::initOnce();
        \GPBMetadata\Cluster\ClusterUser::initOnce();
        \GPBMetadata\Cluster\ClusterDatabase::initOnce();
        $pool->internalAddGeneratedFile(
            '
õ
cluster/cluster_service.prototypedb.protocolcluster/cluster_user.protocluster/cluster_database.proto2Ç
TypeDBCluster]
servers_all&.typedb.protocol.ServerManager.All.Req&.typedb.protocol.ServerManager.All.Rest
users_contains0.typedb.protocol.ClusterUserManager.Contains.Req0.typedb.protocol.ClusterUserManager.Contains.Resn
users_create..typedb.protocol.ClusterUserManager.Create.Req..typedb.protocol.ClusterUserManager.Create.Rese
	users_all+.typedb.protocol.ClusterUserManager.All.Req+.typedb.protocol.ClusterUserManager.All.Rese
user_password).typedb.protocol.ClusterUser.Password.Req).typedb.protocol.ClusterUser.Password.Res\\

user_token&.typedb.protocol.ClusterUser.Token.Req&.typedb.protocol.ClusterUser.Token.Res_
user_delete\'.typedb.protocol.ClusterUser.Delete.Req\'.typedb.protocol.ClusterUser.Delete.Resq
databases_get/.typedb.protocol.ClusterDatabaseManager.Get.Req/.typedb.protocol.ClusterDatabaseManager.Get.Resq
databases_all/.typedb.protocol.ClusterDatabaseManager.All.Req/.typedb.protocol.ClusterDatabaseManager.All.ResB5
com.vaticle.typedb.protocolBClusterServiceProtoˆbproto3'
        , true);

        static::$is_initialized = true;
    }
}

