<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster/cluster_user.proto

namespace GPBMetadata\Cluster;

class ClusterUser
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ë
cluster/cluster_user.prototypedb.protocol"²
ClusterUserManager<
Contains
Req
username (	
Res
contains (:
Create)
Req
username (	
password (	
Res"
All
Req
Res
names (	"­
ClusterUser<
Password)
Req
username (	
password (	
Res6
Token
Req
username (	
Res
token (	(
Delete
Req
username (	
ResB/
com.vaticle.typedb.protocolBClusterUserProtobproto3'
        , true);

        static::$is_initialized = true;
    }
}

