<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster/cluster_server.proto

namespace GPBMetadata\Cluster;

class ClusterServer
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Õ
cluster/cluster_server.prototypedb.protocol"N
ServerManager=
All
Req/
Res(
servers (2.typedb.protocol.Server"
Server
address (	B1
com.vaticle.typedb.protocolBClusterServerProtobproto3'
        , true);

        static::$is_initialized = true;
    }
}

