<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster/cluster_database.proto

namespace GPBMetadata\Cluster;

class ClusterDatabase
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ö
cluster/cluster_database.prototypedb.protocol"¹
ClusterDatabaseManagerU
Get
Req
name (	9
Res2
database (2 .typedb.protocol.ClusterDatabaseH
All
Req:
Res3
	databases (2 .typedb.protocol.ClusterDatabase"©
ClusterDatabase
name (	:
replicas (2(.typedb.protocol.ClusterDatabase.ReplicaL
Replica
address (	
primary (
	preferred (
term (B3
com.vaticle.typedb.protocolBClusterDatabaseProtobproto3'
        , true);

        static::$is_initialized = true;
    }
}

