<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol\ConceptManager\PutRelationType;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.ConceptManager.PutRelationType.Res</code>
 */
class Res extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.typedb.protocol.Type relation_type = 1;</code>
     */
    protected $relation_type = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Typedb\Protocol\Type $relation_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Concept::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Type relation_type = 1;</code>
     * @return \Typedb\Protocol\Type|null
     */
    public function getRelationType()
    {
        return $this->relation_type;
    }

    public function hasRelationType()
    {
        return isset($this->relation_type);
    }

    public function clearRelationType()
    {
        unset($this->relation_type);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Type relation_type = 1;</code>
     * @param \Typedb\Protocol\Type $var
     * @return $this
     */
    public function setRelationType($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Type::class);
        $this->relation_type = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Res::class, \Typedb\Protocol\ConceptManager_PutRelationType_Res::class);

