<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol\Thing\GetRelations;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.Thing.GetRelations.Req</code>
 */
class Req extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.Type role_types = 1;</code>
     */
    private $role_types;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Typedb\Protocol\Type[]|\Google\Protobuf\Internal\RepeatedField $role_types
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Concept::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.Type role_types = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRoleTypes()
    {
        return $this->role_types;
    }

    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.Type role_types = 1;</code>
     * @param \Typedb\Protocol\Type[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRoleTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Typedb\Protocol\Type::class);
        $this->role_types = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Req::class, \Typedb\Protocol\Thing_GetRelations_Req::class);

