<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster/cluster_server.proto

namespace Typedb\Protocol\ServerManager\All;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.ServerManager.All.Res</code>
 */
class Res extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.Server servers = 1;</code>
     */
    private $servers;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Typedb\Protocol\Server[]|\Google\Protobuf\Internal\RepeatedField $servers
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cluster\ClusterServer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.Server servers = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getServers()
    {
        return $this->servers;
    }

    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.Server servers = 1;</code>
     * @param \Typedb\Protocol\Server[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setServers($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Typedb\Protocol\Server::class);
        $this->servers = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Res::class, \Typedb\Protocol\ServerManager_All_Res::class);

