<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol\ThingType\UnsetOwns;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.ThingType.UnsetOwns.Req</code>
 */
class Req extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.typedb.protocol.Type attribute_type = 1;</code>
     */
    protected $attribute_type = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Typedb\Protocol\Type $attribute_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Concept::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Type attribute_type = 1;</code>
     * @return \Typedb\Protocol\Type|null
     */
    public function getAttributeType()
    {
        return $this->attribute_type;
    }

    public function hasAttributeType()
    {
        return isset($this->attribute_type);
    }

    public function clearAttributeType()
    {
        unset($this->attribute_type);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Type attribute_type = 1;</code>
     * @param \Typedb\Protocol\Type $var
     * @return $this
     */
    public function setAttributeType($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Type::class);
        $this->attribute_type = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Req::class, \Typedb\Protocol\ThingType_UnsetOwns_Req::class);

