<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Attribute\Value instead.
     * @deprecated
     */
    class Attribute_Value {}
}
class_exists(Attribute\Value::class);
@trigger_error('Typedb\Protocol\Attribute_Value is deprecated and will be removed in the next major release. Use Typedb\Protocol\Attribute\Value instead', E_USER_DEPRECATED);

