<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\AttributeType\GetInstances instead.
     * @deprecated
     */
    class AttributeType_GetInstances {}
}
class_exists(AttributeType\GetInstances::class);
@trigger_error('Typedb\Protocol\AttributeType_GetInstances is deprecated and will be removed in the next major release. Use Typedb\Protocol\AttributeType\GetInstances instead', E_USER_DEPRECATED);

