<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\AttributeType\GetRegex instead.
     * @deprecated
     */
    class AttributeType_GetRegex {}
}
class_exists(AttributeType\GetRegex::class);
@trigger_error('Typedb\Protocol\AttributeType_GetRegex is deprecated and will be removed in the next major release. Use Typedb\Protocol\AttributeType\GetRegex instead', E_USER_DEPRECATED);

