<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\AttributeType\Put instead.
     * @deprecated
     */
    class AttributeType_Put {}
}
class_exists(AttributeType\Put::class);
@trigger_error('Typedb\Protocol\AttributeType_Put is deprecated and will be removed in the next major release. Use Typedb\Protocol\AttributeType\Put instead', E_USER_DEPRECATED);

