<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\AttributeType\ValueType instead.
     * @deprecated
     */
    class AttributeType_ValueType {}
}
class_exists(AttributeType\ValueType::class);
@trigger_error('Typedb\Protocol\AttributeType_ValueType is deprecated and will be removed in the next major release. Use Typedb\Protocol\AttributeType\ValueType instead', E_USER_DEPRECATED);

