<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\AttributeType\GetSubtypes instead.
     * @deprecated
     */
    class AttributeType_GetSubtypes {}
}
class_exists(AttributeType\GetSubtypes::class);
@trigger_error('Typedb\Protocol\AttributeType_GetSubtypes is deprecated and will be removed in the next major release. Use Typedb\Protocol\AttributeType\GetSubtypes instead', E_USER_DEPRECATED);

