<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Attribute\GetOwners instead.
     * @deprecated
     */
    class Attribute_GetOwners {}
}
class_exists(Attribute\GetOwners::class);
@trigger_error('Typedb\Protocol\Attribute_GetOwners is deprecated and will be removed in the next major release. Use Typedb\Protocol\Attribute\GetOwners instead', E_USER_DEPRECATED);

