<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\AttributeType\Get\Res instead.
     * @deprecated
     */
    class AttributeType_Get_Res {}
}
class_exists(AttributeType\Get\Res::class);
@trigger_error('Typedb\Protocol\AttributeType_Get_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\AttributeType\Get\Res instead', E_USER_DEPRECATED);

