<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\AttributeType\SetRegex\Req instead.
     * @deprecated
     */
    class AttributeType_SetRegex_Req {}
}
class_exists(AttributeType\SetRegex\Req::class);
@trigger_error('Typedb\Protocol\AttributeType_SetRegex_Req is deprecated and will be removed in the next major release. Use Typedb\Protocol\AttributeType\SetRegex\Req instead', E_USER_DEPRECATED);

