<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\AttributeType\Get instead.
     * @deprecated
     */
    class AttributeType_Get {}
}
class_exists(AttributeType\Get::class);
@trigger_error('Typedb\Protocol\AttributeType_Get is deprecated and will be removed in the next major release. Use Typedb\Protocol\AttributeType\Get instead', E_USER_DEPRECATED);

