<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\AttributeType\SetRegex instead.
     * @deprecated
     */
    class AttributeType_SetRegex {}
}
class_exists(AttributeType\SetRegex::class);
@trigger_error('Typedb\Protocol\AttributeType_SetRegex is deprecated and will be removed in the next major release. Use Typedb\Protocol\AttributeType\SetRegex instead', E_USER_DEPRECATED);

