<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\AttributeType\GetRegex\Res instead.
     * @deprecated
     */
    class AttributeType_GetRegex_Res {}
}
class_exists(AttributeType\GetRegex\Res::class);
@trigger_error('Typedb\Protocol\AttributeType_GetRegex_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\AttributeType\GetRegex\Res instead', E_USER_DEPRECATED);

