<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster/cluster_user.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ClusterUser\Password\Res instead.
     * @deprecated
     */
    class ClusterUser_Password_Res {}
}
class_exists(ClusterUser\Password\Res::class);
@trigger_error('Typedb\Protocol\ClusterUser_Password_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\ClusterUser\Password\Res instead', E_USER_DEPRECATED);

