<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster/cluster_database.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ClusterDatabaseManager\Get instead.
     * @deprecated
     */
    class ClusterDatabaseManager_Get {}
}
class_exists(ClusterDatabaseManager\Get::class);
@trigger_error('Typedb\Protocol\ClusterDatabaseManager_Get is deprecated and will be removed in the next major release. Use Typedb\Protocol\ClusterDatabaseManager\Get instead', E_USER_DEPRECATED);

