<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster/cluster_database.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ClusterDatabase\Replica instead.
     * @deprecated
     */
    class ClusterDatabase_Replica {}
}
class_exists(ClusterDatabase\Replica::class);
@trigger_error('Typedb\Protocol\ClusterDatabase_Replica is deprecated and will be removed in the next major release. Use Typedb\Protocol\ClusterDatabase\Replica instead', E_USER_DEPRECATED);

