<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster/cluster_database.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ClusterDatabaseManager\All\Res instead.
     * @deprecated
     */
    class ClusterDatabaseManager_All_Res {}
}
class_exists(ClusterDatabaseManager\All\Res::class);
@trigger_error('Typedb\Protocol\ClusterDatabaseManager_All_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\ClusterDatabaseManager\All\Res instead', E_USER_DEPRECATED);

