<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster/cluster_user.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ClusterUser\Token instead.
     * @deprecated
     */
    class ClusterUser_Token {}
}
class_exists(ClusterUser\Token::class);
@trigger_error('Typedb\Protocol\ClusterUser_Token is deprecated and will be removed in the next major release. Use Typedb\Protocol\ClusterUser\Token instead', E_USER_DEPRECATED);

