<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster/cluster_user.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ClusterUserManager\Contains instead.
     * @deprecated
     */
    class ClusterUserManager_Contains {}
}
class_exists(ClusterUserManager\Contains::class);
@trigger_error('Typedb\Protocol\ClusterUserManager_Contains is deprecated and will be removed in the next major release. Use Typedb\Protocol\ClusterUserManager\Contains instead', E_USER_DEPRECATED);

