<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster/cluster_user.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ClusterUserManager\Contains\Req instead.
     * @deprecated
     */
    class ClusterUserManager_Contains_Req {}
}
class_exists(ClusterUserManager\Contains\Req::class);
@trigger_error('Typedb\Protocol\ClusterUserManager_Contains_Req is deprecated and will be removed in the next major release. Use Typedb\Protocol\ClusterUserManager\Contains\Req instead', E_USER_DEPRECATED);

