<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster/cluster_user.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ClusterUser\Password instead.
     * @deprecated
     */
    class ClusterUser_Password {}
}
class_exists(ClusterUser\Password::class);
@trigger_error('Typedb\Protocol\ClusterUser_Password is deprecated and will be removed in the next major release. Use Typedb\Protocol\ClusterUser\Password instead', E_USER_DEPRECATED);

