<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster/cluster_database.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ClusterDatabaseManager\All instead.
     * @deprecated
     */
    class ClusterDatabaseManager_All {}
}
class_exists(ClusterDatabaseManager\All::class);
@trigger_error('Typedb\Protocol\ClusterDatabaseManager_All is deprecated and will be removed in the next major release. Use Typedb\Protocol\ClusterDatabaseManager\All instead', E_USER_DEPRECATED);

