<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster/cluster_user.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ClusterUserManager\Create\Res instead.
     * @deprecated
     */
    class ClusterUserManager_Create_Res {}
}
class_exists(ClusterUserManager\Create\Res::class);
@trigger_error('Typedb\Protocol\ClusterUserManager_Create_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\ClusterUserManager\Create\Res instead', E_USER_DEPRECATED);

