<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster/cluster_database.proto

namespace Typedb\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.ClusterDatabaseManager</code>
 */
class ClusterDatabaseManager extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cluster\ClusterDatabase::initOnce();
        parent::__construct($data);
    }

}

