<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster/cluster_user.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ClusterUser\Delete instead.
     * @deprecated
     */
    class ClusterUser_Delete {}
}
class_exists(ClusterUser\Delete::class);
@trigger_error('Typedb\Protocol\ClusterUser_Delete is deprecated and will be removed in the next major release. Use Typedb\Protocol\ClusterUser\Delete instead', E_USER_DEPRECATED);

