<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ConceptManager\PutRelationType\Res instead.
     * @deprecated
     */
    class ConceptManager_PutRelationType_Res {}
}
class_exists(ConceptManager\PutRelationType\Res::class);
@trigger_error('Typedb\Protocol\ConceptManager_PutRelationType_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\ConceptManager\PutRelationType\Res instead', E_USER_DEPRECATED);

