<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ConceptManager\GetThing instead.
     * @deprecated
     */
    class ConceptManager_GetThing {}
}
class_exists(ConceptManager\GetThing::class);
@trigger_error('Typedb\Protocol\ConceptManager_GetThing is deprecated and will be removed in the next major release. Use Typedb\Protocol\ConceptManager\GetThing instead', E_USER_DEPRECATED);

