<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ConceptManager\GetThingType instead.
     * @deprecated
     */
    class ConceptManager_GetThingType {}
}
class_exists(ConceptManager\GetThingType::class);
@trigger_error('Typedb\Protocol\ConceptManager_GetThingType is deprecated and will be removed in the next major release. Use Typedb\Protocol\ConceptManager\GetThingType instead', E_USER_DEPRECATED);

