<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ConceptManager\GetThing\Res instead.
     * @deprecated
     */
    class ConceptManager_GetThing_Res {}
}
class_exists(ConceptManager\GetThing\Res::class);
@trigger_error('Typedb\Protocol\ConceptManager_GetThing_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\ConceptManager\GetThing\Res instead', E_USER_DEPRECATED);

