<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ConceptManager\PutEntityType instead.
     * @deprecated
     */
    class ConceptManager_PutEntityType {}
}
class_exists(ConceptManager\PutEntityType::class);
@trigger_error('Typedb\Protocol\ConceptManager_PutEntityType is deprecated and will be removed in the next major release. Use Typedb\Protocol\ConceptManager\PutEntityType instead', E_USER_DEPRECATED);

