<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ConceptManager\PutRelationType instead.
     * @deprecated
     */
    class ConceptManager_PutRelationType {}
}
class_exists(ConceptManager\PutRelationType::class);
@trigger_error('Typedb\Protocol\ConceptManager_PutRelationType is deprecated and will be removed in the next major release. Use Typedb\Protocol\ConceptManager\PutRelationType instead', E_USER_DEPRECATED);

