<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/answer.proto

namespace Typedb\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.ConceptMapGroup</code>
 */
class ConceptMapGroup extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.typedb.protocol.Concept owner = 1;</code>
     */
    protected $owner = null;
    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.ConceptMap concept_maps = 2;</code>
     */
    private $concept_maps;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Typedb\Protocol\Concept $owner
     *     @type \Typedb\Protocol\ConceptMap[]|\Google\Protobuf\Internal\RepeatedField $concept_maps
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Answer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Concept owner = 1;</code>
     * @return \Typedb\Protocol\Concept|null
     */
    public function getOwner()
    {
        return $this->owner;
    }

    public function hasOwner()
    {
        return isset($this->owner);
    }

    public function clearOwner()
    {
        unset($this->owner);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Concept owner = 1;</code>
     * @param \Typedb\Protocol\Concept $var
     * @return $this
     */
    public function setOwner($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Concept::class);
        $this->owner = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.ConceptMap concept_maps = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConceptMaps()
    {
        return $this->concept_maps;
    }

    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.ConceptMap concept_maps = 2;</code>
     * @param \Typedb\Protocol\ConceptMap[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConceptMaps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Typedb\Protocol\ConceptMap::class);
        $this->concept_maps = $arr;

        return $this;
    }

}

