<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ConceptManager\PutAttributeType instead.
     * @deprecated
     */
    class ConceptManager_PutAttributeType {}
}
class_exists(ConceptManager\PutAttributeType::class);
@trigger_error('Typedb\Protocol\ConceptManager_PutAttributeType is deprecated and will be removed in the next major release. Use Typedb\Protocol\ConceptManager\PutAttributeType instead', E_USER_DEPRECATED);

