<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/answer.proto

namespace Typedb\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.ConceptMap</code>
 */
class ConceptMap extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, .typedb.protocol.Concept> map = 1;</code>
     */
    private $map;
    /**
     * Generated from protobuf field <code>.typedb.protocol.Explainables explainables = 2;</code>
     */
    protected $explainables = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $map
     *     @type \Typedb\Protocol\Explainables $explainables
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Answer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, .typedb.protocol.Concept> map = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMap()
    {
        return $this->map;
    }

    /**
     * Generated from protobuf field <code>map<string, .typedb.protocol.Concept> map = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMap($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Typedb\Protocol\Concept::class);
        $this->map = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Explainables explainables = 2;</code>
     * @return \Typedb\Protocol\Explainables|null
     */
    public function getExplainables()
    {
        return $this->explainables;
    }

    public function hasExplainables()
    {
        return isset($this->explainables);
    }

    public function clearExplainables()
    {
        unset($this->explainables);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Explainables explainables = 2;</code>
     * @param \Typedb\Protocol\Explainables $var
     * @return $this
     */
    public function setExplainables($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Explainables::class);
        $this->explainables = $var;

        return $this;
    }

}

