<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ConceptManager\GetThing\Req instead.
     * @deprecated
     */
    class ConceptManager_GetThing_Req {}
}
class_exists(ConceptManager\GetThing\Req::class);
@trigger_error('Typedb\Protocol\ConceptManager_GetThing_Req is deprecated and will be removed in the next major release. Use Typedb\Protocol\ConceptManager\GetThing\Req instead', E_USER_DEPRECATED);

