<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/core_database.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\CoreDatabase\Schema instead.
     * @deprecated
     */
    class CoreDatabase_Schema {}
}
class_exists(CoreDatabase\Schema::class);
@trigger_error('Typedb\Protocol\CoreDatabase_Schema is deprecated and will be removed in the next major release. Use Typedb\Protocol\CoreDatabase\Schema instead', E_USER_DEPRECATED);

