<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/core_database.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\CoreDatabaseManager\Contains\Res instead.
     * @deprecated
     */
    class CoreDatabaseManager_Contains_Res {}
}
class_exists(CoreDatabaseManager\Contains\Res::class);
@trigger_error('Typedb\Protocol\CoreDatabaseManager_Contains_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\CoreDatabaseManager\Contains\Res instead', E_USER_DEPRECATED);

