<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/core_database.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\CoreDatabaseManager\All\Res instead.
     * @deprecated
     */
    class CoreDatabaseManager_All_Res {}
}
class_exists(CoreDatabaseManager\All\Res::class);
@trigger_error('Typedb\Protocol\CoreDatabaseManager_All_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\CoreDatabaseManager\All\Res instead', E_USER_DEPRECATED);

