<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/core_database.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\CoreDatabaseManager\Create instead.
     * @deprecated
     */
    class CoreDatabaseManager_Create {}
}
class_exists(CoreDatabaseManager\Create::class);
@trigger_error('Typedb\Protocol\CoreDatabaseManager_Create is deprecated and will be removed in the next major release. Use Typedb\Protocol\CoreDatabaseManager\Create instead', E_USER_DEPRECATED);

