<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/core_database.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\CoreDatabase\Delete\Req instead.
     * @deprecated
     */
    class CoreDatabase_Delete_Req {}
}
class_exists(CoreDatabase\Delete\Req::class);
@trigger_error('Typedb\Protocol\CoreDatabase_Delete_Req is deprecated and will be removed in the next major release. Use Typedb\Protocol\CoreDatabase\Delete\Req instead', E_USER_DEPRECATED);

