<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/core_database.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\CoreDatabase\Schema\Res instead.
     * @deprecated
     */
    class CoreDatabase_Schema_Res {}
}
class_exists(CoreDatabase\Schema\Res::class);
@trigger_error('Typedb\Protocol\CoreDatabase_Schema_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\CoreDatabase\Schema\Res instead', E_USER_DEPRECATED);

