<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\EntityType\Create instead.
     * @deprecated
     */
    class EntityType_Create {}
}
class_exists(EntityType\Create::class);
@trigger_error('Typedb\Protocol\EntityType_Create is deprecated and will be removed in the next major release. Use Typedb\Protocol\EntityType\Create instead', E_USER_DEPRECATED);

