<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/answer.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Explainables\Owned instead.
     * @deprecated
     */
    class Explainables_Owned {}
}
class_exists(Explainables\Owned::class);
@trigger_error('Typedb\Protocol\Explainables_Owned is deprecated and will be removed in the next major release. Use Typedb\Protocol\Explainables\Owned instead', E_USER_DEPRECATED);

