<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/answer.proto

namespace Typedb\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.Explainable</code>
 */
class Explainable extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string conjunction = 1;</code>
     */
    protected $conjunction = '';
    /**
     * Generated from protobuf field <code>int64 id = 2;</code>
     */
    protected $id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $conjunction
     *     @type int|string $id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Answer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string conjunction = 1;</code>
     * @return string
     */
    public function getConjunction()
    {
        return $this->conjunction;
    }

    /**
     * Generated from protobuf field <code>string conjunction = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setConjunction($var)
    {
        GPBUtil::checkString($var, True);
        $this->conjunction = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 id = 2;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

}

