<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/logic.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Explanation\VarList instead.
     * @deprecated
     */
    class Explanation_VarList {}
}
class_exists(Explanation\VarList::class);
@trigger_error('Typedb\Protocol\Explanation_VarList is deprecated and will be removed in the next major release. Use Typedb\Protocol\Explanation\VarList instead', E_USER_DEPRECATED);

