<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/answer.proto

namespace Typedb\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.Explainables</code>
 */
class Explainables extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, .typedb.protocol.Explainable> relations = 1;</code>
     */
    private $relations;
    /**
     * Generated from protobuf field <code>map<string, .typedb.protocol.Explainable> attributes = 2;</code>
     */
    private $attributes;
    /**
     * Generated from protobuf field <code>map<string, .typedb.protocol.Explainables.Owned> ownerships = 3;</code>
     */
    private $ownerships;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $relations
     *     @type array|\Google\Protobuf\Internal\MapField $attributes
     *     @type array|\Google\Protobuf\Internal\MapField $ownerships
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Answer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, .typedb.protocol.Explainable> relations = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getRelations()
    {
        return $this->relations;
    }

    /**
     * Generated from protobuf field <code>map<string, .typedb.protocol.Explainable> relations = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setRelations($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Typedb\Protocol\Explainable::class);
        $this->relations = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .typedb.protocol.Explainable> attributes = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * Generated from protobuf field <code>map<string, .typedb.protocol.Explainable> attributes = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAttributes($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Typedb\Protocol\Explainable::class);
        $this->attributes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .typedb.protocol.Explainables.Owned> ownerships = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getOwnerships()
    {
        return $this->ownerships;
    }

    /**
     * Generated from protobuf field <code>map<string, .typedb.protocol.Explainables.Owned> ownerships = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setOwnerships($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Typedb\Protocol\Explainables\Owned::class);
        $this->ownerships = $arr;

        return $this;
    }

}

