<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/logic.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\LogicManager\GetRules\ResPart instead.
     * @deprecated
     */
    class LogicManager_GetRules_ResPart {}
}
class_exists(LogicManager\GetRules\ResPart::class);
@trigger_error('Typedb\Protocol\LogicManager_GetRules_ResPart is deprecated and will be removed in the next major release. Use Typedb\Protocol\LogicManager\GetRules\ResPart instead', E_USER_DEPRECATED);

