<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/logic.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\LogicManager\GetRules instead.
     * @deprecated
     */
    class LogicManager_GetRules {}
}
class_exists(LogicManager\GetRules::class);
@trigger_error('Typedb\Protocol\LogicManager_GetRules is deprecated and will be removed in the next major release. Use Typedb\Protocol\LogicManager\GetRules instead', E_USER_DEPRECATED);

