<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/logic.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\LogicManager\GetRule\Req instead.
     * @deprecated
     */
    class LogicManager_GetRule_Req {}
}
class_exists(LogicManager\GetRule\Req::class);
@trigger_error('Typedb\Protocol\LogicManager_GetRule_Req is deprecated and will be removed in the next major release. Use Typedb\Protocol\LogicManager\GetRule\Req instead', E_USER_DEPRECATED);

