<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/answer.proto

namespace Typedb\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.NumericGroup</code>
 */
class NumericGroup extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.typedb.protocol.Concept owner = 1;</code>
     */
    protected $owner = null;
    /**
     * Generated from protobuf field <code>.typedb.protocol.Numeric number = 2;</code>
     */
    protected $number = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Typedb\Protocol\Concept $owner
     *     @type \Typedb\Protocol\Numeric $number
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Answer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Concept owner = 1;</code>
     * @return \Typedb\Protocol\Concept|null
     */
    public function getOwner()
    {
        return $this->owner;
    }

    public function hasOwner()
    {
        return isset($this->owner);
    }

    public function clearOwner()
    {
        unset($this->owner);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Concept owner = 1;</code>
     * @param \Typedb\Protocol\Concept $var
     * @return $this
     */
    public function setOwner($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Concept::class);
        $this->owner = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Numeric number = 2;</code>
     * @return \Typedb\Protocol\Numeric|null
     */
    public function getNumber()
    {
        return $this->number;
    }

    public function hasNumber()
    {
        return isset($this->number);
    }

    public function clearNumber()
    {
        unset($this->number);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Numeric number = 2;</code>
     * @param \Typedb\Protocol\Numeric $var
     * @return $this
     */
    public function setNumber($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Numeric::class);
        $this->number = $var;

        return $this;
    }

}

