<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/query.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\QueryManager\Delete instead.
     * @deprecated
     */
    class QueryManager_Delete {}
}
class_exists(QueryManager\Delete::class);
@trigger_error('Typedb\Protocol\QueryManager_Delete is deprecated and will be removed in the next major release. Use Typedb\Protocol\QueryManager\Delete instead', E_USER_DEPRECATED);

