<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/query.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\QueryManager\Define instead.
     * @deprecated
     */
    class QueryManager_Define {}
}
class_exists(QueryManager\Define::class);
@trigger_error('Typedb\Protocol\QueryManager_Define is deprecated and will be removed in the next major release. Use Typedb\Protocol\QueryManager\Define instead', E_USER_DEPRECATED);

