<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/query.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\QueryManager\Explain instead.
     * @deprecated
     */
    class QueryManager_Explain {}
}
class_exists(QueryManager\Explain::class);
@trigger_error('Typedb\Protocol\QueryManager_Explain is deprecated and will be removed in the next major release. Use Typedb\Protocol\QueryManager\Explain instead', E_USER_DEPRECATED);

