<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/query.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\QueryManager\MatchAggregate instead.
     * @deprecated
     */
    class QueryManager_MatchAggregate {}
}
class_exists(QueryManager\MatchAggregate::class);
@trigger_error('Typedb\Protocol\QueryManager_MatchAggregate is deprecated and will be removed in the next major release. Use Typedb\Protocol\QueryManager\MatchAggregate instead', E_USER_DEPRECATED);

