<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/query.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\QueryManager\Req instead.
     * @deprecated
     */
    class QueryManager_Req {}
}
class_exists(QueryManager\Req::class);
@trigger_error('Typedb\Protocol\QueryManager_Req is deprecated and will be removed in the next major release. Use Typedb\Protocol\QueryManager\Req instead', E_USER_DEPRECATED);

