<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/query.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\QueryManager\MatchGroup instead.
     * @deprecated
     */
    class QueryManager_MatchGroup {}
}
class_exists(QueryManager\MatchGroup::class);
@trigger_error('Typedb\Protocol\QueryManager_MatchGroup is deprecated and will be removed in the next major release. Use Typedb\Protocol\QueryManager\MatchGroup instead', E_USER_DEPRECATED);

