<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/query.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\QueryManager\MatchGroupAggregate instead.
     * @deprecated
     */
    class QueryManager_MatchGroupAggregate {}
}
class_exists(QueryManager\MatchGroupAggregate::class);
@trigger_error('Typedb\Protocol\QueryManager_MatchGroupAggregate is deprecated and will be removed in the next major release. Use Typedb\Protocol\QueryManager\MatchGroupAggregate instead', E_USER_DEPRECATED);

