<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/query.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\QueryManager\Update instead.
     * @deprecated
     */
    class QueryManager_Update {}
}
class_exists(QueryManager\Update::class);
@trigger_error('Typedb\Protocol\QueryManager_Update is deprecated and will be removed in the next major release. Use Typedb\Protocol\QueryManager\Update instead', E_USER_DEPRECATED);

