<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/query.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\QueryManager\Undefine\Res instead.
     * @deprecated
     */
    class QueryManager_Undefine_Res {}
}
class_exists(QueryManager\Undefine\Res::class);
@trigger_error('Typedb\Protocol\QueryManager_Undefine_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\QueryManager\Undefine\Res instead', E_USER_DEPRECATED);

