<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/query.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\QueryManager\Insert\ResPart instead.
     * @deprecated
     */
    class QueryManager_Insert_ResPart {}
}
class_exists(QueryManager\Insert\ResPart::class);
@trigger_error('Typedb\Protocol\QueryManager_Insert_ResPart is deprecated and will be removed in the next major release. Use Typedb\Protocol\QueryManager\Insert\ResPart instead', E_USER_DEPRECATED);

