<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/query.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\QueryManager\PBMatch instead.
     * @deprecated
     */
    class QueryManager_Match {}
}
class_exists(QueryManager\PBMatch::class);
@trigger_error('Typedb\Protocol\QueryManager_Match is deprecated and will be removed in the next major release. Use Typedb\Protocol\QueryManager\PBMatch instead', E_USER_DEPRECATED);

