<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/query.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\QueryManager\Update\ResPart instead.
     * @deprecated
     */
    class QueryManager_Update_ResPart {}
}
class_exists(QueryManager\Update\ResPart::class);
@trigger_error('Typedb\Protocol\QueryManager_Update_ResPart is deprecated and will be removed in the next major release. Use Typedb\Protocol\QueryManager\Update\ResPart instead', E_USER_DEPRECATED);

