<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\RelationType\Create instead.
     * @deprecated
     */
    class RelationType_Create {}
}
class_exists(RelationType\Create::class);
@trigger_error('Typedb\Protocol\RelationType_Create is deprecated and will be removed in the next major release. Use Typedb\Protocol\RelationType\Create instead', E_USER_DEPRECATED);

