<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\RelationType\GetRelates instead.
     * @deprecated
     */
    class RelationType_GetRelates {}
}
class_exists(RelationType\GetRelates::class);
@trigger_error('Typedb\Protocol\RelationType_GetRelates is deprecated and will be removed in the next major release. Use Typedb\Protocol\RelationType\GetRelates instead', E_USER_DEPRECATED);

