<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Relation\RemovePlayer\Res instead.
     * @deprecated
     */
    class Relation_RemovePlayer_Res {}
}
class_exists(Relation\RemovePlayer\Res::class);
@trigger_error('Typedb\Protocol\Relation_RemovePlayer_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\Relation\RemovePlayer\Res instead', E_USER_DEPRECATED);

