<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\RelationType\Create\Res instead.
     * @deprecated
     */
    class RelationType_Create_Res {}
}
class_exists(RelationType\Create\Res::class);
@trigger_error('Typedb\Protocol\RelationType_Create_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\RelationType\Create\Res instead', E_USER_DEPRECATED);

