<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Relation\GetPlayersByRoleType\ResPart instead.
     * @deprecated
     */
    class Relation_GetPlayersByRoleType_ResPart {}
}
class_exists(Relation\GetPlayersByRoleType\ResPart::class);
@trigger_error('Typedb\Protocol\Relation_GetPlayersByRoleType_ResPart is deprecated and will be removed in the next major release. Use Typedb\Protocol\Relation\GetPlayersByRoleType\ResPart instead', E_USER_DEPRECATED);

