<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Relation\RemovePlayer instead.
     * @deprecated
     */
    class Relation_RemovePlayer {}
}
class_exists(Relation\RemovePlayer::class);
@trigger_error('Typedb\Protocol\Relation_RemovePlayer is deprecated and will be removed in the next major release. Use Typedb\Protocol\Relation\RemovePlayer instead', E_USER_DEPRECATED);

