<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Relation\AddPlayer instead.
     * @deprecated
     */
    class Relation_AddPlayer {}
}
class_exists(Relation\AddPlayer::class);
@trigger_error('Typedb\Protocol\Relation_AddPlayer is deprecated and will be removed in the next major release. Use Typedb\Protocol\Relation\AddPlayer instead', E_USER_DEPRECATED);

