<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Relation\GetRelating\ResPart instead.
     * @deprecated
     */
    class Relation_GetRelating_ResPart {}
}
class_exists(Relation\GetRelating\ResPart::class);
@trigger_error('Typedb\Protocol\Relation_GetRelating_ResPart is deprecated and will be removed in the next major release. Use Typedb\Protocol\Relation\GetRelating\ResPart instead', E_USER_DEPRECATED);

