<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\RelationType\UnsetRelates instead.
     * @deprecated
     */
    class RelationType_UnsetRelates {}
}
class_exists(RelationType\UnsetRelates::class);
@trigger_error('Typedb\Protocol\RelationType_UnsetRelates is deprecated and will be removed in the next major release. Use Typedb\Protocol\RelationType\UnsetRelates instead', E_USER_DEPRECATED);

