<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\RelationType\GetRelates\Req instead.
     * @deprecated
     */
    class RelationType_GetRelates_Req {}
}
class_exists(RelationType\GetRelates\Req::class);
@trigger_error('Typedb\Protocol\RelationType_GetRelates_Req is deprecated and will be removed in the next major release. Use Typedb\Protocol\RelationType\GetRelates\Req instead', E_USER_DEPRECATED);

