<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\RelationType\UnsetRelates\Res instead.
     * @deprecated
     */
    class RelationType_UnsetRelates_Res {}
}
class_exists(RelationType\UnsetRelates\Res::class);
@trigger_error('Typedb\Protocol\RelationType_UnsetRelates_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\RelationType\UnsetRelates\Res instead', E_USER_DEPRECATED);

