<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\RelationType\SetRelates instead.
     * @deprecated
     */
    class RelationType_SetRelates {}
}
class_exists(RelationType\SetRelates::class);
@trigger_error('Typedb\Protocol\RelationType_SetRelates is deprecated and will be removed in the next major release. Use Typedb\Protocol\RelationType\SetRelates instead', E_USER_DEPRECATED);

