<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\RelationType\GetRelatesForRoleLabel instead.
     * @deprecated
     */
    class RelationType_GetRelatesForRoleLabel {}
}
class_exists(RelationType\GetRelatesForRoleLabel::class);
@trigger_error('Typedb\Protocol\RelationType_GetRelatesForRoleLabel is deprecated and will be removed in the next major release. Use Typedb\Protocol\RelationType\GetRelatesForRoleLabel instead', E_USER_DEPRECATED);

