<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Relation\GetPlayersByRoleType\RoleTypeWithPlayer instead.
     * @deprecated
     */
    class Relation_GetPlayersByRoleType_RoleTypeWithPlayer {}
}
class_exists(Relation\GetPlayersByRoleType\RoleTypeWithPlayer::class);
@trigger_error('Typedb\Protocol\Relation_GetPlayersByRoleType_RoleTypeWithPlayer is deprecated and will be removed in the next major release. Use Typedb\Protocol\Relation\GetPlayersByRoleType\RoleTypeWithPlayer instead', E_USER_DEPRECATED);

