<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Relation\GetPlayersByRoleType instead.
     * @deprecated
     */
    class Relation_GetPlayersByRoleType {}
}
class_exists(Relation\GetPlayersByRoleType::class);
@trigger_error('Typedb\Protocol\Relation_GetPlayersByRoleType is deprecated and will be removed in the next major release. Use Typedb\Protocol\Relation\GetPlayersByRoleType instead', E_USER_DEPRECATED);

