<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Relation\GetPlayers instead.
     * @deprecated
     */
    class Relation_GetPlayers {}
}
class_exists(Relation\GetPlayers::class);
@trigger_error('Typedb\Protocol\Relation_GetPlayers is deprecated and will be removed in the next major release. Use Typedb\Protocol\Relation\GetPlayers instead', E_USER_DEPRECATED);

