<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\RoleType\GetPlayers\Req instead.
     * @deprecated
     */
    class RoleType_GetPlayers_Req {}
}
class_exists(RoleType\GetPlayers\Req::class);
@trigger_error('Typedb\Protocol\RoleType_GetPlayers_Req is deprecated and will be removed in the next major release. Use Typedb\Protocol\RoleType\GetPlayers\Req instead', E_USER_DEPRECATED);

