<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/logic.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Rule\Delete instead.
     * @deprecated
     */
    class Rule_Delete {}
}
class_exists(Rule\Delete::class);
@trigger_error('Typedb\Protocol\Rule_Delete is deprecated and will be removed in the next major release. Use Typedb\Protocol\Rule\Delete instead', E_USER_DEPRECATED);

