<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/logic.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Rule\SetLabel instead.
     * @deprecated
     */
    class Rule_SetLabel {}
}
class_exists(Rule\SetLabel::class);
@trigger_error('Typedb\Protocol\Rule_SetLabel is deprecated and will be removed in the next major release. Use Typedb\Protocol\Rule\SetLabel instead', E_USER_DEPRECATED);

