<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/logic.proto

namespace Typedb\Protocol;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.Rule</code>
 */
class Rule extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string label = 1;</code>
     */
    protected $label = '';
    /**
     * Generated from protobuf field <code>string when = 2;</code>
     */
    protected $when = '';
    /**
     * Generated from protobuf field <code>string then = 3;</code>
     */
    protected $then = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $label
     *     @type string $when
     *     @type string $then
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Logic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string label = 1;</code>
     * @return string
     */
    public function getLabel()
    {
        return $this->label;
    }

    /**
     * Generated from protobuf field <code>string label = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLabel($var)
    {
        GPBUtil::checkString($var, True);
        $this->label = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string when = 2;</code>
     * @return string
     */
    public function getWhen()
    {
        return $this->when;
    }

    /**
     * Generated from protobuf field <code>string when = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setWhen($var)
    {
        GPBUtil::checkString($var, True);
        $this->when = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string then = 3;</code>
     * @return string
     */
    public function getThen()
    {
        return $this->then;
    }

    /**
     * Generated from protobuf field <code>string then = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setThen($var)
    {
        GPBUtil::checkString($var, True);
        $this->then = $var;

        return $this;
    }

}

