<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/logic.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Rule\Res instead.
     * @deprecated
     */
    class Rule_Res {}
}
class_exists(Rule\Res::class);
@trigger_error('Typedb\Protocol\Rule_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\Rule\Res instead', E_USER_DEPRECATED);

