<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/logic.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Rule\SetLabel\Req instead.
     * @deprecated
     */
    class Rule_SetLabel_Req {}
}
class_exists(Rule\SetLabel\Req::class);
@trigger_error('Typedb\Protocol\Rule_SetLabel_Req is deprecated and will be removed in the next major release. Use Typedb\Protocol\Rule\SetLabel\Req instead', E_USER_DEPRECATED);

