<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/logic.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Rule\SetLabel\Res instead.
     * @deprecated
     */
    class Rule_SetLabel_Res {}
}
class_exists(Rule\SetLabel\Res::class);
@trigger_error('Typedb\Protocol\Rule_SetLabel_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\Rule\SetLabel\Res instead', E_USER_DEPRECATED);

