<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster/cluster_server.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ServerManager\All\Req instead.
     * @deprecated
     */
    class ServerManager_All_Req {}
}
class_exists(ServerManager\All\Req::class);
@trigger_error('Typedb\Protocol\ServerManager_All_Req is deprecated and will be removed in the next major release. Use Typedb\Protocol\ServerManager\All\Req instead', E_USER_DEPRECATED);

