<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/session.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Session\Close\Res instead.
     * @deprecated
     */
    class Session_Close_Res {}
}
class_exists(Session\Close\Res::class);
@trigger_error('Typedb\Protocol\Session_Close_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\Session\Close\Res instead', E_USER_DEPRECATED);

