<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/session.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Session\Type instead.
     * @deprecated
     */
    class Session_Type {}
}
class_exists(Session\Type::class);
@trigger_error('Typedb\Protocol\Session_Type is deprecated and will be removed in the next major release. Use Typedb\Protocol\Session\Type instead', E_USER_DEPRECATED);

