<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/session.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Session\Open instead.
     * @deprecated
     */
    class Session_Open {}
}
class_exists(Session\Open::class);
@trigger_error('Typedb\Protocol\Session_Open is deprecated and will be removed in the next major release. Use Typedb\Protocol\Session\Open instead', E_USER_DEPRECATED);

