<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/session.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Session\Pulse\Req instead.
     * @deprecated
     */
    class Session_Pulse_Req {}
}
class_exists(Session\Pulse\Req::class);
@trigger_error('Typedb\Protocol\Session_Pulse_Req is deprecated and will be removed in the next major release. Use Typedb\Protocol\Session\Pulse\Req instead', E_USER_DEPRECATED);

