<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/session.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Session\Pulse instead.
     * @deprecated
     */
    class Session_Pulse {}
}
class_exists(Session\Pulse::class);
@trigger_error('Typedb\Protocol\Session_Pulse is deprecated and will be removed in the next major release. Use Typedb\Protocol\Session\Pulse instead', E_USER_DEPRECATED);

