<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/session.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Session\Close instead.
     * @deprecated
     */
    class Session_Close {}
}
class_exists(Session\Close::class);
@trigger_error('Typedb\Protocol\Session_Close is deprecated and will be removed in the next major release. Use Typedb\Protocol\Session\Close instead', E_USER_DEPRECATED);

