<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Thing\Delete instead.
     * @deprecated
     */
    class Thing_Delete {}
}
class_exists(Thing\Delete::class);
@trigger_error('Typedb\Protocol\Thing_Delete is deprecated and will be removed in the next major release. Use Typedb\Protocol\Thing\Delete instead', E_USER_DEPRECATED);

