<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Thing\GetRelations\ResPart instead.
     * @deprecated
     */
    class Thing_GetRelations_ResPart {}
}
class_exists(Thing\GetRelations\ResPart::class);
@trigger_error('Typedb\Protocol\Thing_GetRelations_ResPart is deprecated and will be removed in the next major release. Use Typedb\Protocol\Thing\GetRelations\ResPart instead', E_USER_DEPRECATED);

