<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ThingType\SetAbstract\Res instead.
     * @deprecated
     */
    class ThingType_SetAbstract_Res {}
}
class_exists(ThingType\SetAbstract\Res::class);
@trigger_error('Typedb\Protocol\ThingType_SetAbstract_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\ThingType\SetAbstract\Res instead', E_USER_DEPRECATED);

