<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Thing\GetHas instead.
     * @deprecated
     */
    class Thing_GetHas {}
}
class_exists(Thing\GetHas::class);
@trigger_error('Typedb\Protocol\Thing_GetHas is deprecated and will be removed in the next major release. Use Typedb\Protocol\Thing\GetHas instead', E_USER_DEPRECATED);

