<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ThingType\UnsetPlays instead.
     * @deprecated
     */
    class ThingType_UnsetPlays {}
}
class_exists(ThingType\UnsetPlays::class);
@trigger_error('Typedb\Protocol\ThingType_UnsetPlays is deprecated and will be removed in the next major release. Use Typedb\Protocol\ThingType\UnsetPlays instead', E_USER_DEPRECATED);

