<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Thing\SetHas\Res instead.
     * @deprecated
     */
    class Thing_SetHas_Res {}
}
class_exists(Thing\SetHas\Res::class);
@trigger_error('Typedb\Protocol\Thing_SetHas_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\Thing\SetHas\Res instead', E_USER_DEPRECATED);

