<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ThingType\UnsetOwns instead.
     * @deprecated
     */
    class ThingType_UnsetOwns {}
}
class_exists(ThingType\UnsetOwns::class);
@trigger_error('Typedb\Protocol\ThingType_UnsetOwns is deprecated and will be removed in the next major release. Use Typedb\Protocol\ThingType\UnsetOwns instead', E_USER_DEPRECATED);

