<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Thing\GetRelations instead.
     * @deprecated
     */
    class Thing_GetRelations {}
}
class_exists(Thing\GetRelations::class);
@trigger_error('Typedb\Protocol\Thing_GetRelations is deprecated and will be removed in the next major release. Use Typedb\Protocol\Thing\GetRelations instead', E_USER_DEPRECATED);

