<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ThingType\GetPlays instead.
     * @deprecated
     */
    class ThingType_GetPlays {}
}
class_exists(ThingType\GetPlays::class);
@trigger_error('Typedb\Protocol\ThingType_GetPlays is deprecated and will be removed in the next major release. Use Typedb\Protocol\ThingType\GetPlays instead', E_USER_DEPRECATED);

