<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Thing\GetPlaying\Req instead.
     * @deprecated
     */
    class Thing_GetPlaying_Req {}
}
class_exists(Thing\GetPlaying\Req::class);
@trigger_error('Typedb\Protocol\Thing_GetPlaying_Req is deprecated and will be removed in the next major release. Use Typedb\Protocol\Thing\GetPlaying\Req instead', E_USER_DEPRECATED);

