<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ThingType\UnsetPlays\Req instead.
     * @deprecated
     */
    class ThingType_UnsetPlays_Req {}
}
class_exists(ThingType\UnsetPlays\Req::class);
@trigger_error('Typedb\Protocol\ThingType_UnsetPlays_Req is deprecated and will be removed in the next major release. Use Typedb\Protocol\ThingType\UnsetPlays\Req instead', E_USER_DEPRECATED);

