<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Thing\Delete\Res instead.
     * @deprecated
     */
    class Thing_Delete_Res {}
}
class_exists(Thing\Delete\Res::class);
@trigger_error('Typedb\Protocol\Thing_Delete_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\Thing\Delete\Res instead', E_USER_DEPRECATED);

