<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ThingType\UnsetOwns\Res instead.
     * @deprecated
     */
    class ThingType_UnsetOwns_Res {}
}
class_exists(ThingType\UnsetOwns\Res::class);
@trigger_error('Typedb\Protocol\ThingType_UnsetOwns_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\ThingType\UnsetOwns\Res instead', E_USER_DEPRECATED);

