<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Thing\GetType\Req instead.
     * @deprecated
     */
    class Thing_GetType_Req {}
}
class_exists(Thing\GetType\Req::class);
@trigger_error('Typedb\Protocol\Thing_GetType_Req is deprecated and will be removed in the next major release. Use Typedb\Protocol\Thing\GetType\Req instead', E_USER_DEPRECATED);

