<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ThingType\UnsetAbstract instead.
     * @deprecated
     */
    class ThingType_UnsetAbstract {}
}
class_exists(ThingType\UnsetAbstract::class);
@trigger_error('Typedb\Protocol\ThingType_UnsetAbstract is deprecated and will be removed in the next major release. Use Typedb\Protocol\ThingType\UnsetAbstract instead', E_USER_DEPRECATED);

