<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Thing\GetType\Res instead.
     * @deprecated
     */
    class Thing_GetType_Res {}
}
class_exists(Thing\GetType\Res::class);
@trigger_error('Typedb\Protocol\Thing_GetType_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\Thing\GetType\Res instead', E_USER_DEPRECATED);

