<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ThingType\GetInstances instead.
     * @deprecated
     */
    class ThingType_GetInstances {}
}
class_exists(ThingType\GetInstances::class);
@trigger_error('Typedb\Protocol\ThingType_GetInstances is deprecated and will be removed in the next major release. Use Typedb\Protocol\ThingType\GetInstances instead', E_USER_DEPRECATED);

