<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ThingType\SetOwns instead.
     * @deprecated
     */
    class ThingType_SetOwns {}
}
class_exists(ThingType\SetOwns::class);
@trigger_error('Typedb\Protocol\ThingType_SetOwns is deprecated and will be removed in the next major release. Use Typedb\Protocol\ThingType\SetOwns instead', E_USER_DEPRECATED);

