<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Thing\GetPlaying instead.
     * @deprecated
     */
    class Thing_GetPlaying {}
}
class_exists(Thing\GetPlaying::class);
@trigger_error('Typedb\Protocol\Thing_GetPlaying is deprecated and will be removed in the next major release. Use Typedb\Protocol\Thing\GetPlaying instead', E_USER_DEPRECATED);

