<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Thing\GetType instead.
     * @deprecated
     */
    class Thing_GetType {}
}
class_exists(Thing\GetType::class);
@trigger_error('Typedb\Protocol\Thing_GetType is deprecated and will be removed in the next major release. Use Typedb\Protocol\Thing\GetType instead', E_USER_DEPRECATED);

