<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Thing\UnsetHas\Req instead.
     * @deprecated
     */
    class Thing_UnsetHas_Req {}
}
class_exists(Thing\UnsetHas\Req::class);
@trigger_error('Typedb\Protocol\Thing_UnsetHas_Req is deprecated and will be removed in the next major release. Use Typedb\Protocol\Thing\UnsetHas\Req instead', E_USER_DEPRECATED);

