<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ThingType\GetOwns instead.
     * @deprecated
     */
    class ThingType_GetOwns {}
}
class_exists(ThingType\GetOwns::class);
@trigger_error('Typedb\Protocol\ThingType_GetOwns is deprecated and will be removed in the next major release. Use Typedb\Protocol\ThingType\GetOwns instead', E_USER_DEPRECATED);

