<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Thing\UnsetHas instead.
     * @deprecated
     */
    class Thing_UnsetHas {}
}
class_exists(Thing\UnsetHas::class);
@trigger_error('Typedb\Protocol\Thing_UnsetHas is deprecated and will be removed in the next major release. Use Typedb\Protocol\Thing\UnsetHas instead', E_USER_DEPRECATED);

