<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Thing\SetHas instead.
     * @deprecated
     */
    class Thing_SetHas {}
}
class_exists(Thing\SetHas::class);
@trigger_error('Typedb\Protocol\Thing_SetHas is deprecated and will be removed in the next major release. Use Typedb\Protocol\Thing\SetHas instead', E_USER_DEPRECATED);

