<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ThingType\SetAbstract instead.
     * @deprecated
     */
    class ThingType_SetAbstract {}
}
class_exists(ThingType\SetAbstract::class);
@trigger_error('Typedb\Protocol\ThingType_SetAbstract is deprecated and will be removed in the next major release. Use Typedb\Protocol\ThingType\SetAbstract instead', E_USER_DEPRECATED);

