<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ThingType\GetInstances\ResPart instead.
     * @deprecated
     */
    class ThingType_GetInstances_ResPart {}
}
class_exists(ThingType\GetInstances\ResPart::class);
@trigger_error('Typedb\Protocol\ThingType_GetInstances_ResPart is deprecated and will be removed in the next major release. Use Typedb\Protocol\ThingType\GetInstances\ResPart instead', E_USER_DEPRECATED);

