<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ThingType\SetPlays instead.
     * @deprecated
     */
    class ThingType_SetPlays {}
}
class_exists(ThingType\SetPlays::class);
@trigger_error('Typedb\Protocol\ThingType_SetPlays is deprecated and will be removed in the next major release. Use Typedb\Protocol\ThingType\SetPlays instead', E_USER_DEPRECATED);

