<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\ThingType\SetOwns\Res instead.
     * @deprecated
     */
    class ThingType_SetOwns_Res {}
}
class_exists(ThingType\SetOwns\Res::class);
@trigger_error('Typedb\Protocol\ThingType_SetOwns_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\ThingType\SetOwns\Res instead', E_USER_DEPRECATED);

