<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/transaction.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Transaction\Server instead.
     * @deprecated
     */
    class Transaction_Server {}
}
class_exists(Transaction\Server::class);
@trigger_error('Typedb\Protocol\Transaction_Server is deprecated and will be removed in the next major release. Use Typedb\Protocol\Transaction\Server instead', E_USER_DEPRECATED);

