<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/transaction.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Transaction\Rollback\Req instead.
     * @deprecated
     */
    class Transaction_Rollback_Req {}
}
class_exists(Transaction\Rollback\Req::class);
@trigger_error('Typedb\Protocol\Transaction_Rollback_Req is deprecated and will be removed in the next major release. Use Typedb\Protocol\Transaction\Rollback\Req instead', E_USER_DEPRECATED);

