<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/transaction.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Transaction\Commit instead.
     * @deprecated
     */
    class Transaction_Commit {}
}
class_exists(Transaction\Commit::class);
@trigger_error('Typedb\Protocol\Transaction_Commit is deprecated and will be removed in the next major release. Use Typedb\Protocol\Transaction\Commit instead', E_USER_DEPRECATED);

