<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/transaction.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Transaction\Rollback instead.
     * @deprecated
     */
    class Transaction_Rollback {}
}
class_exists(Transaction\Rollback::class);
@trigger_error('Typedb\Protocol\Transaction_Rollback is deprecated and will be removed in the next major release. Use Typedb\Protocol\Transaction\Rollback instead', E_USER_DEPRECATED);

