<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/transaction.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Transaction\Type instead.
     * @deprecated
     */
    class Transaction_Type {}
}
class_exists(Transaction\Type::class);
@trigger_error('Typedb\Protocol\Transaction_Type is deprecated and will be removed in the next major release. Use Typedb\Protocol\Transaction\Type instead', E_USER_DEPRECATED);

