<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/transaction.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Transaction\Open instead.
     * @deprecated
     */
    class Transaction_Open {}
}
class_exists(Transaction\Open::class);
@trigger_error('Typedb\Protocol\Transaction_Open is deprecated and will be removed in the next major release. Use Typedb\Protocol\Transaction\Open instead', E_USER_DEPRECATED);

