<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/transaction.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Transaction\Stream\State instead.
     * @deprecated
     */
    class Transaction_Stream_State {}
}
class_exists(Transaction\Stream\State::class);
@trigger_error('Typedb\Protocol\Transaction_Stream_State is deprecated and will be removed in the next major release. Use Typedb\Protocol\Transaction\Stream\State instead', E_USER_DEPRECATED);

