<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/transaction.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Transaction\Open\Res instead.
     * @deprecated
     */
    class Transaction_Open_Res {}
}
class_exists(Transaction\Open\Res::class);
@trigger_error('Typedb\Protocol\Transaction_Open_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\Transaction\Open\Res instead', E_USER_DEPRECATED);

