<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/transaction.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Transaction\Stream instead.
     * @deprecated
     */
    class Transaction_Stream {}
}
class_exists(Transaction\Stream::class);
@trigger_error('Typedb\Protocol\Transaction_Stream is deprecated and will be removed in the next major release. Use Typedb\Protocol\Transaction\Stream instead', E_USER_DEPRECATED);

