<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/transaction.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Transaction\Stream\ResPart instead.
     * @deprecated
     */
    class Transaction_Stream_ResPart {}
}
class_exists(Transaction\Stream\ResPart::class);
@trigger_error('Typedb\Protocol\Transaction_Stream_ResPart is deprecated and will be removed in the next major release. Use Typedb\Protocol\Transaction\Stream\ResPart instead', E_USER_DEPRECATED);

