<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Type\GetSupertype\Req instead.
     * @deprecated
     */
    class Type_GetSupertype_Req {}
}
class_exists(Type\GetSupertype\Req::class);
@trigger_error('Typedb\Protocol\Type_GetSupertype_Req is deprecated and will be removed in the next major release. Use Typedb\Protocol\Type\GetSupertype\Req instead', E_USER_DEPRECATED);

