<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Type\GetSubtypes\ResPart instead.
     * @deprecated
     */
    class Type_GetSubtypes_ResPart {}
}
class_exists(Type\GetSubtypes\ResPart::class);
@trigger_error('Typedb\Protocol\Type_GetSubtypes_ResPart is deprecated and will be removed in the next major release. Use Typedb\Protocol\Type\GetSubtypes\ResPart instead', E_USER_DEPRECATED);

