<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Type\Encoding instead.
     * @deprecated
     */
    class Type_Encoding {}
}
class_exists(Type\Encoding::class);
@trigger_error('Typedb\Protocol\Type_Encoding is deprecated and will be removed in the next major release. Use Typedb\Protocol\Type\Encoding instead', E_USER_DEPRECATED);

