<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Type\IsAbstract instead.
     * @deprecated
     */
    class Type_IsAbstract {}
}
class_exists(Type\IsAbstract::class);
@trigger_error('Typedb\Protocol\Type_IsAbstract is deprecated and will be removed in the next major release. Use Typedb\Protocol\Type\IsAbstract instead', E_USER_DEPRECATED);

