<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Type\Res instead.
     * @deprecated
     */
    class Type_Res {}
}
class_exists(Type\Res::class);
@trigger_error('Typedb\Protocol\Type_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\Type\Res instead', E_USER_DEPRECATED);

