<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Type\GetSupertype instead.
     * @deprecated
     */
    class Type_GetSupertype {}
}
class_exists(Type\GetSupertype::class);
@trigger_error('Typedb\Protocol\Type_GetSupertype is deprecated and will be removed in the next major release. Use Typedb\Protocol\Type\GetSupertype instead', E_USER_DEPRECATED);

