<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Type\Delete\Res instead.
     * @deprecated
     */
    class Type_Delete_Res {}
}
class_exists(Type\Delete\Res::class);
@trigger_error('Typedb\Protocol\Type_Delete_Res is deprecated and will be removed in the next major release. Use Typedb\Protocol\Type\Delete\Res instead', E_USER_DEPRECATED);

