<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Type\SetLabel instead.
     * @deprecated
     */
    class Type_SetLabel {}
}
class_exists(Type\SetLabel::class);
@trigger_error('Typedb\Protocol\Type_SetLabel is deprecated and will be removed in the next major release. Use Typedb\Protocol\Type\SetLabel instead', E_USER_DEPRECATED);

