<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Type\SetSupertype\Req instead.
     * @deprecated
     */
    class Type_SetSupertype_Req {}
}
class_exists(Type\SetSupertype\Req::class);
@trigger_error('Typedb\Protocol\Type_SetSupertype_Req is deprecated and will be removed in the next major release. Use Typedb\Protocol\Type\SetSupertype\Req instead', E_USER_DEPRECATED);

