<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol;

if (false) {
    /**
     * This class is deprecated. Use Typedb\Protocol\Type\SetSupertype instead.
     * @deprecated
     */
    class Type_SetSupertype {}
}
class_exists(Type\SetSupertype::class);
@trigger_error('Typedb\Protocol\Type_SetSupertype is deprecated and will be removed in the next major release. Use Typedb\Protocol\Type\SetSupertype instead', E_USER_DEPRECATED);

