<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/logic.proto

namespace Typedb\Protocol\LogicManager;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.LogicManager.ResPart</code>
 */
class ResPart extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.typedb.protocol.LogicManager.GetRules.ResPart get_rules_res_part = 1;</code>
     */
    protected $get_rules_res_part = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Typedb\Protocol\LogicManager\GetRules\ResPart $get_rules_res_part
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Logic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.LogicManager.GetRules.ResPart get_rules_res_part = 1;</code>
     * @return \Typedb\Protocol\LogicManager\GetRules\ResPart|null
     */
    public function getGetRulesResPart()
    {
        return $this->get_rules_res_part;
    }

    public function hasGetRulesResPart()
    {
        return isset($this->get_rules_res_part);
    }

    public function clearGetRulesResPart()
    {
        unset($this->get_rules_res_part);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.LogicManager.GetRules.ResPart get_rules_res_part = 1;</code>
     * @param \Typedb\Protocol\LogicManager\GetRules\ResPart $var
     * @return $this
     */
    public function setGetRulesResPart($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\LogicManager\GetRules\ResPart::class);
        $this->get_rules_res_part = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ResPart::class, \Typedb\Protocol\LogicManager_ResPart::class);

