<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/answer.proto

namespace Typedb\Protocol\Explainables;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.Explainables.Owned</code>
 */
class Owned extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, .typedb.protocol.Explainable> owned = 1;</code>
     */
    private $owned;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $owned
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Answer::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, .typedb.protocol.Explainable> owned = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getOwned()
    {
        return $this->owned;
    }

    /**
     * Generated from protobuf field <code>map<string, .typedb.protocol.Explainable> owned = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setOwned($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Typedb\Protocol\Explainable::class);
        $this->owned = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Owned::class, \Typedb\Protocol\Explainables_Owned::class);

