<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cluster/cluster_user.proto

namespace Typedb\Protocol\ClusterUser;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.ClusterUser.Delete</code>
 */
class Delete extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Cluster\ClusterUser::initOnce();
        parent::__construct($data);
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Delete::class, \Typedb\Protocol\ClusterUser_Delete::class);

