<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/query.proto

namespace Typedb\Protocol\QueryManager\Explain;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.QueryManager.Explain.Req</code>
 */
class Req extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 explainable_id = 1;</code>
     */
    protected $explainable_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $explainable_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 explainable_id = 1;</code>
     * @return int|string
     */
    public function getExplainableId()
    {
        return $this->explainable_id;
    }

    /**
     * Generated from protobuf field <code>int64 explainable_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExplainableId($var)
    {
        GPBUtil::checkInt64($var);
        $this->explainable_id = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Req::class, \Typedb\Protocol\QueryManager_Explain_Req::class);

