<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/query.proto

namespace Typedb\Protocol\QueryManager\Explain;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.QueryManager.Explain.ResPart</code>
 */
class ResPart extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.Explanation explanations = 1;</code>
     */
    private $explanations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Typedb\Protocol\Explanation[]|\Google\Protobuf\Internal\RepeatedField $explanations
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Query::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.Explanation explanations = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getExplanations()
    {
        return $this->explanations;
    }

    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.Explanation explanations = 1;</code>
     * @param \Typedb\Protocol\Explanation[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setExplanations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Typedb\Protocol\Explanation::class);
        $this->explanations = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ResPart::class, \Typedb\Protocol\QueryManager_Explain_ResPart::class);

