<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol\RoleType\GetRelationTypes;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.RoleType.GetRelationTypes.ResPart</code>
 */
class ResPart extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.Type relation_types = 1;</code>
     */
    private $relation_types;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Typedb\Protocol\Type[]|\Google\Protobuf\Internal\RepeatedField $relation_types
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Concept::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.Type relation_types = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRelationTypes()
    {
        return $this->relation_types;
    }

    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.Type relation_types = 1;</code>
     * @param \Typedb\Protocol\Type[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRelationTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Typedb\Protocol\Type::class);
        $this->relation_types = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ResPart::class, \Typedb\Protocol\RoleType_GetRelationTypes_ResPart::class);

