<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol\Type\IsAbstract;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.Type.IsAbstract.Res</code>
 */
class Res extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool abstract = 1;</code>
     */
    protected $abstract = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $abstract
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Concept::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool abstract = 1;</code>
     * @return bool
     */
    public function getAbstract()
    {
        return $this->abstract;
    }

    /**
     * Generated from protobuf field <code>bool abstract = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setAbstract($var)
    {
        GPBUtil::checkBool($var);
        $this->abstract = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Res::class, \Typedb\Protocol\Type_IsAbstract_Res::class);

