<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/core_database.proto

namespace GPBMetadata\Core;

class CoreDatabase
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
í
core/core_database.prototypedb.protocol"™
CoreDatabaseManager8
Contains
Req
name (	
Res
contains ($
Create
Req
name (	
Res"
All
Req
Res
names (	"j
CoreDatabase4
Schema
Req
name (	
Res
schema (	$
Delete
Req
name (	
ResB0
com.vaticle.typedb.protocolBCoreDatabaseProtobproto3'
        , true);

        static::$is_initialized = true;
    }
}

