<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/core_service.proto

namespace GPBMetadata\Core;

class CoreService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\CoreDatabase::initOnce();
        \GPBMetadata\Common\Session::initOnce();
        \GPBMetadata\Common\Transaction::initOnce();
        $pool->internalAddGeneratedFile(
            '
³
core/core_service.prototypedb.protocolcommon/session.protocommon/transaction.proto2š
TypeDBz
databases_contains1.typedb.protocol.CoreDatabaseManager.Contains.Req1.typedb.protocol.CoreDatabaseManager.Contains.Rest
databases_create/.typedb.protocol.CoreDatabaseManager.Create.Req/.typedb.protocol.CoreDatabaseManager.Create.Resk
databases_all,.typedb.protocol.CoreDatabaseManager.All.Req,.typedb.protocol.CoreDatabaseManager.All.Rese
database_schema(.typedb.protocol.CoreDatabase.Schema.Req(.typedb.protocol.CoreDatabase.Schema.Rese
database_delete(.typedb.protocol.CoreDatabase.Delete.Req(.typedb.protocol.CoreDatabase.Delete.ResT
session_open!.typedb.protocol.Session.Open.Req!.typedb.protocol.Session.Open.ResW
session_close".typedb.protocol.Session.Close.Req".typedb.protocol.Session.Close.ResW
session_pulse".typedb.protocol.Session.Pulse.Req".typedb.protocol.Session.Pulse.Res[
transaction#.typedb.protocol.Transaction.Client#.typedb.protocol.Transaction.Server(0B2
com.vaticle.typedb.protocolBCoreServiceProtoˆbproto3'
        , true);

        static::$is_initialized = true;
    }
}

