<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol\Attribute;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.Attribute.Value</code>
 */
class Value extends \Google\Protobuf\Internal\Message
{
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $string
     *     @type bool $boolean
     *     @type int|string $long
     *     @type float $double
     *     @type int|string $date_time
     *           time since epoch in milliseconds
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Concept::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string string = 1;</code>
     * @return string
     */
    public function getString()
    {
        return $this->readOneof(1);
    }

    public function hasString()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>string string = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setString($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool boolean = 2;</code>
     * @return bool
     */
    public function getBoolean()
    {
        return $this->readOneof(2);
    }

    public function hasBoolean()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>bool boolean = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setBoolean($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 long = 3;</code>
     * @return int|string
     */
    public function getLong()
    {
        return $this->readOneof(3);
    }

    public function hasLong()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>int64 long = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLong($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>double double = 4;</code>
     * @return float
     */
    public function getDouble()
    {
        return $this->readOneof(4);
    }

    public function hasDouble()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>double double = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setDouble($var)
    {
        GPBUtil::checkDouble($var);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * time since epoch in milliseconds
     *
     * Generated from protobuf field <code>int64 date_time = 5;</code>
     * @return int|string
     */
    public function getDateTime()
    {
        return $this->readOneof(5);
    }

    public function hasDateTime()
    {
        return $this->hasOneof(5);
    }

    /**
     * time since epoch in milliseconds
     *
     * Generated from protobuf field <code>int64 date_time = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Value::class, \Typedb\Protocol\Attribute_Value::class);

