<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol\Relation\RemovePlayer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.Relation.RemovePlayer.Req</code>
 */
class Req extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.typedb.protocol.Type role_type = 1;</code>
     */
    protected $role_type = null;
    /**
     * Generated from protobuf field <code>.typedb.protocol.Thing player = 2;</code>
     */
    protected $player = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Typedb\Protocol\Type $role_type
     *     @type \Typedb\Protocol\Thing $player
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Concept::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Type role_type = 1;</code>
     * @return \Typedb\Protocol\Type|null
     */
    public function getRoleType()
    {
        return $this->role_type;
    }

    public function hasRoleType()
    {
        return isset($this->role_type);
    }

    public function clearRoleType()
    {
        unset($this->role_type);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Type role_type = 1;</code>
     * @param \Typedb\Protocol\Type $var
     * @return $this
     */
    public function setRoleType($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Type::class);
        $this->role_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Thing player = 2;</code>
     * @return \Typedb\Protocol\Thing|null
     */
    public function getPlayer()
    {
        return $this->player;
    }

    public function hasPlayer()
    {
        return isset($this->player);
    }

    public function clearPlayer()
    {
        unset($this->player);
    }

    /**
     * Generated from protobuf field <code>.typedb.protocol.Thing player = 2;</code>
     * @param \Typedb\Protocol\Thing $var
     * @return $this
     */
    public function setPlayer($var)
    {
        GPBUtil::checkMessage($var, \Typedb\Protocol\Thing::class);
        $this->player = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Req::class, \Typedb\Protocol\Relation_RemovePlayer_Req::class);

