<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol\Thing\GetHas;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.Thing.GetHas.Req</code>
 */
class Req extends \Google\Protobuf\Internal\Message
{
    /**
     * Only one filter can be set at a time (attribute_types or keys_only). repeated can't be used in a oneof
     *
     * Generated from protobuf field <code>repeated .typedb.protocol.Type attribute_types = 1;</code>
     */
    private $attribute_types;
    /**
     * Generated from protobuf field <code>bool keys_only = 2;</code>
     */
    protected $keys_only = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Typedb\Protocol\Type[]|\Google\Protobuf\Internal\RepeatedField $attribute_types
     *           Only one filter can be set at a time (attribute_types or keys_only). repeated can't be used in a oneof
     *     @type bool $keys_only
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Concept::initOnce();
        parent::__construct($data);
    }

    /**
     * Only one filter can be set at a time (attribute_types or keys_only). repeated can't be used in a oneof
     *
     * Generated from protobuf field <code>repeated .typedb.protocol.Type attribute_types = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttributeTypes()
    {
        return $this->attribute_types;
    }

    /**
     * Only one filter can be set at a time (attribute_types or keys_only). repeated can't be used in a oneof
     *
     * Generated from protobuf field <code>repeated .typedb.protocol.Type attribute_types = 1;</code>
     * @param \Typedb\Protocol\Type[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttributeTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Typedb\Protocol\Type::class);
        $this->attribute_types = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool keys_only = 2;</code>
     * @return bool
     */
    public function getKeysOnly()
    {
        return $this->keys_only;
    }

    /**
     * Generated from protobuf field <code>bool keys_only = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setKeysOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->keys_only = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Req::class, \Typedb\Protocol\Thing_GetHas_Req::class);

