<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/concept.proto

namespace Typedb\Protocol\RoleType\GetPlayers;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>typedb.protocol.RoleType.GetPlayers.ResPart</code>
 */
class ResPart extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.Type thing_types = 1;</code>
     */
    private $thing_types;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Typedb\Protocol\Type[]|\Google\Protobuf\Internal\RepeatedField $thing_types
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Concept::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.Type thing_types = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getThingTypes()
    {
        return $this->thing_types;
    }

    /**
     * Generated from protobuf field <code>repeated .typedb.protocol.Type thing_types = 1;</code>
     * @param \Typedb\Protocol\Type[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setThingTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Typedb\Protocol\Type::class);
        $this->thing_types = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ResPart::class, \Typedb\Protocol\RoleType_GetPlayers_ResPart::class);

